#!/bin/sh
# 58:12 Connect — Asterisk PBX container entrypoint.
#
# Pulls fresh pjsip.conf / extensions.conf / voicemail.conf from the FastAPI
# backend, writes them to /etc/asterisk, then starts (or HUP-reloads) asterisk.
# Runs on a configurable interval (PBX_RELOAD_INTERVAL, default 60s).
#
# Required env (set in docker-compose.yml):
#   PBX_API_URL          — e.g. http://localhost/api/pbx
#   PBX_TOKEN            — admin JWT (one-off; rotate via Admin → PBX → Token)
#   PBX_RELOAD_INTERVAL  — seconds between config polls (default 60)

set -e

PBX_API_URL="${PBX_API_URL:-http://localhost/api/pbx}"
PBX_RELOAD_INTERVAL="${PBX_RELOAD_INTERVAL:-60}"
LAST_HASH=""

pull_config() {
  if [ -z "$PBX_TOKEN" ]; then
    echo "[pbx-entrypoint] PBX_TOKEN not set — skipping config sync. Writing stub config."
    mkdir -p /etc/asterisk
    if [ ! -f /etc/asterisk/pjsip.conf ]; then
      cat > /etc/asterisk/pjsip.conf <<EOF
; Awaiting PBX_TOKEN — no SIP endpoints configured yet.
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
EOF
      echo "" > /etc/asterisk/extensions.conf
      echo "" > /etc/asterisk/voicemail.conf
    fi
    write_manager_conf
    return
  fi
  write_manager_conf
  for fname in pjsip.conf extensions.conf voicemail.conf; do
    tmpfile=$(mktemp)
    if curl -fsS -H "Authorization: Bearer $PBX_TOKEN" "$PBX_API_URL/config/$fname" -o "$tmpfile" 2>/dev/null; then
      if ! cmp -s "$tmpfile" "/etc/asterisk/$fname" 2>/dev/null; then
        mv "$tmpfile" "/etc/asterisk/$fname"
        echo "[pbx-entrypoint] $fname updated"
        return 0
      else
        rm -f "$tmpfile"
      fi
    else
      echo "[pbx-entrypoint] WARN: could not fetch $fname from $PBX_API_URL"
      rm -f "$tmpfile"
    fi
  done
  return 1
}

write_manager_conf() {
  # The AMI user the FastAPI backend uses to issue reload/originate/status.
  # AMI_SECRET must match what's set on the backend pod.
  if [ -z "$AMI_SECRET" ]; then
    echo "[pbx-entrypoint] AMI_SECRET not set — Originate / live-status disabled."
    return
  fi
  if [ ! -f /etc/asterisk/manager.conf ] || ! grep -q "^secret = $AMI_SECRET$" /etc/asterisk/manager.conf 2>/dev/null; then
    cat > /etc/asterisk/manager.conf <<EOF
; manager.conf — auto-generated by 58:12 Connect entrypoint
[general]
enabled = yes
port = 5038
bindaddr = 0.0.0.0

[${AMI_USERNAME:-connect-app}]
secret = $AMI_SECRET
permit = 0.0.0.0/0
read = system,call,reporting,cdr
write = system,call,originate,reporting
deny = 0.0.0.0/0
permit = 127.0.0.1/255.255.255.255
permit = 10.0.0.0/255.0.0.0
permit = 172.16.0.0/255.240.0.0
permit = 192.168.0.0/255.255.0.0
EOF
    echo "[pbx-entrypoint] manager.conf written"
  fi
}

reload_or_start_asterisk() {
  if pidof asterisk >/dev/null 2>&1; then
    echo "[pbx-entrypoint] reloading Asterisk..."
    asterisk -rx "core reload" || true
  else
    echo "[pbx-entrypoint] starting Asterisk..."
    asterisk -f -U asterisk -G asterisk &
  fi
}

# Initial pull + start
pull_config || true
reload_or_start_asterisk

# Reload loop
while true; do
  sleep "$PBX_RELOAD_INTERVAL"
  if pull_config; then
    reload_or_start_asterisk
  fi
done
