"""Shipment Tracker — 40' container collection + packing.

Admins (and only admins) manage a shipment. Anyone with the shareable token can:
  • view the wishlist (still needed + already acquired)
  • mark items as donated, optionally with a donor name (no auth, no email)
  • watch the running shipment weight + 40' container cap

Per-shipment editor PIN:
  Admins may set an `access_pin` on a shipment. Anyone with the public token
  + PIN can authenticate via `POST /public/shipments/{token}/login` and get a
  short-lived HMAC-signed `edit_token` (header `X-Shipment-Edit-Token`).
  That token unlocks a mirror of the admin edit endpoints, scoped to this
  shipment only — used for trusted volunteers who shouldn't have full system
  admin rights but need to maintain the manifest.

AI packing scenarios are generated by Gemini-3-flash from the live item/pallet
state — text-only, fits inside a Markdown box on both the admin + public UIs.

40' high-cube container reference:
  Internal:  12.03 m × 2.35 m × 2.69 m   (≈ 76 m³)
  Max payload: ~26,000 kg
"""
from fastapi import APIRouter, Depends, HTTPException, Request, Response
from typing import Optional, List
import os
import os as _os
from deps import db, get_current_user, _audit, require_admin, logger
from datetime import datetime, timezone, timedelta
import uuid
import hmac
import hashlib
import base64
import secrets

router = APIRouter(prefix="/api", tags=["shipments"])

# 40' high-cube interior dimensions in cm — used in the AI packing prompt.
CONTAINER_40FT_HC = {"length_cm": 1203, "width_cm": 235, "height_cm": 269, "max_payload_kg": 26000}

VALID_PRIORITIES = {"low", "normal", "high", "urgent"}
VALID_STATUSES = {"planning", "collecting", "packed", "shipped", "delivered", "cancelled"}


# ============================================================
# Shipment edit-PIN — let admins delegate manifest maintenance
# to trusted volunteers without giving them system admin access.
# ============================================================

_PIN_SECRET = os.environ.get("JWT_SECRET", "dev-secret-fallback").encode()
_PIN_SALT = b"shipment-edit-v1"
EDIT_TOKEN_TTL_HOURS = 12


def _hash_pin(pin: str) -> str:
    """SHA-256(salt + pin) → hex. Plenty for low-stakes, non-PII gating."""
    return hashlib.sha256(_PIN_SALT + pin.encode("utf-8")).hexdigest()


def _make_edit_token(shipment_id: str) -> str:
    """HMAC-signed 'shipment_id:expires_iso' token. Base64-url encoded."""
    expires_at = (datetime.now(timezone.utc) + timedelta(hours=EDIT_TOKEN_TTL_HOURS)).isoformat()
    payload = f"{shipment_id}|{expires_at}"
    sig = hmac.new(_PIN_SECRET, payload.encode(), hashlib.sha256).hexdigest()
    return base64.urlsafe_b64encode(f"{payload}|{sig}".encode()).decode().rstrip("=")


def _verify_edit_token(token: str) -> Optional[str]:
    """Return the shipment_id if the token is valid + unexpired, else None."""
    try:
        padded = token + "=" * (-len(token) % 4)
        raw = base64.urlsafe_b64decode(padded).decode()
        shipment_id, expires_at, sig = raw.rsplit("|", 2)
    except Exception:
        return None
    payload = f"{shipment_id}|{expires_at}"
    expected = hmac.new(_PIN_SECRET, payload.encode(), hashlib.sha256).hexdigest()
    if not hmac.compare_digest(sig, expected):
        return None
    try:
        if datetime.fromisoformat(expires_at) < datetime.now(timezone.utc):
            return None
    except Exception:
        return None
    return shipment_id


async def require_shipment_editor(request: Request, token: str):
    """Dependency for public-edit endpoints.

    Accepts EITHER:
      • a logged-in admin (via the normal Authorization: Bearer JWT)
      • an X-Shipment-Edit-Token header that decodes to THIS shipment's id
    """
    s = await db.shipments.find_one({"token": token}, {"_id": 0, "id": 1, "status": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    if s.get("status") == "cancelled":
        raise HTTPException(status_code=404, detail="Shipment not found")
    # 1) admin path: try the standard JWT auth, if present
    auth = request.headers.get("Authorization") or ""
    if auth.startswith("Bearer "):
        try:
            from deps import _decode_jwt   # type: ignore
        except Exception:
            _decode_jwt = None
        if _decode_jwt:
            try:
                payload = _decode_jwt(auth.split(" ", 1)[1])
                user_id = payload.get("user_id") or payload.get("id")
                user = await db.users.find_one({"id": user_id}, {"_id": 0})
                if user and user.get("role") in ("admin", "super_admin"):
                    return {"shipment_id": s["id"], "actor": "admin", "user": user}
            except Exception:
                pass
    # 2) edit-token path — accept it either from the header (POST/PUT calls)
    #    or from a `?edit_token=...` query param fallback (browser-native GET).
    edit_token = (request.headers.get("X-Shipment-Edit-Token") or "").strip()
    if not edit_token:
        edit_token = (request.query_params.get("edit_token") or "").strip()
    if edit_token:
        sid = _verify_edit_token(edit_token)
        if sid == s["id"]:
            return {"shipment_id": s["id"], "actor": "pin"}
    raise HTTPException(status_code=401, detail="Edit-PIN required for this shipment")


# ============================================================
# Admin CRUD (require_admin)
# ============================================================

@router.get("/shipments")
async def list_shipments(current_user: dict = Depends(require_admin)):
    """All shipments. Newest first. Sponsor-token NOT included in the list view
    to avoid accidentally leaking tokens into screenshots — fetch the detail
    endpoint to get the token + share URL."""
    rows = await db.shipments.find({}, {"_id": 0, "token": 0}).sort("created_at", -1).to_list(500)
    # Lightweight rollup so the list shows progress at-a-glance
    for s in rows:
        items = s.get("items") or []
        s["item_count"] = len(items)
        s["total_needed"] = sum(int(i.get("qty_needed") or 0) for i in items)
        s["total_acquired"] = sum(int(i.get("qty_acquired") or 0) for i in items)
        s["total_weight_kg"] = round(sum(
            (float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0)) for i in items
        ), 1)
        # Drop heavy nested arrays from the list payload
        s.pop("items", None)
        s.pop("pallets", None)
    return rows


@router.post("/shipments")
async def create_shipment(data: dict, current_user: dict = Depends(require_admin)):
    name = (data.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="name is required")
    token = secrets.token_urlsafe(20)  # ~26-char URL-safe random
    doc = {
        "id": f"sh_{uuid.uuid4().hex[:10]}",
        "token": token,
        "name": name[:120],
        "dest_country": (data.get("dest_country") or "Uganda")[:60],
        "description": (data.get("description") or "")[:1000],
        "target_ship_date": (data.get("target_ship_date") or "")[:10],
        "status": "planning",
        "max_payload_kg": float(data.get("max_payload_kg") or CONTAINER_40FT_HC["max_payload_kg"]),
        "container_dims_cm": CONTAINER_40FT_HC,
        "items": [],
        "pallets": [],
        "ai_packing_text": "",
        "ai_packing_generated_at": None,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "created_by": current_user["id"],
        "created_by_name": current_user.get("name", ""),
    }
    await db.shipments.insert_one(doc)
    doc.pop("_id", None)
    await _audit(current_user["id"], "create", "shipment", doc["id"], {"name": name})
    return doc


@router.get("/shipments/{shipment_id}")
async def get_shipment(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Full shipment detail INCLUDING the token + the share URL — only admins
    see this. Public visitors use the /api/public/shipments/{token} path."""
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    # Build a share URL hint — the FE will format it with REACT_APP_BACKEND_URL → site root
    s["share_path"] = f"/donate/shipment/{s.get('token', '')}"
    return s


@router.put("/shipments/{shipment_id}")
async def update_shipment(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"name", "dest_country", "description", "target_ship_date", "status",
               "max_payload_kg", "container_dims_cm"}
    set_ops = {k: v for k, v in data.items() if k in allowed}
    if "status" in set_ops and set_ops["status"] not in VALID_STATUSES:
        raise HTTPException(status_code=400, detail=f"status must be one of {sorted(VALID_STATUSES)}")
    if "container_dims_cm" in set_ops:
        c = set_ops["container_dims_cm"] or {}
        set_ops["container_dims_cm"] = {
            "length_cm": max(50, float(c.get("length_cm") or CONTAINER_40FT_HC["length_cm"])),
            "width_cm":  max(50, float(c.get("width_cm")  or CONTAINER_40FT_HC["width_cm"])),
            "height_cm": max(50, float(c.get("height_cm") or CONTAINER_40FT_HC["height_cm"])),
            "max_payload_kg": float(c.get("max_payload_kg") or CONTAINER_40FT_HC["max_payload_kg"]),
        }
    set_ops["updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one({"id": shipment_id}, {"$set": set_ops})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return {"updated": True}


@router.post("/shipments/{shipment_id}/set-pin")
async def set_shipment_pin(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    """Set / change / clear the per-shipment access PIN.
    Body: { pin: '4-32 chars, blank to clear' }
    The hash is one-way; we never store the plaintext."""
    pin = (data.get("pin") or "").strip()
    if pin and (len(pin) < 4 or len(pin) > 32):
        raise HTTPException(status_code=400, detail="PIN must be 4-32 characters")
    update = {"access_pin_hash": _hash_pin(pin) if pin else None,
              "access_pin_set_at": datetime.now(timezone.utc).isoformat() if pin else None}
    r = await db.shipments.update_one({"id": shipment_id}, {"$set": update})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    await _audit(current_user["id"], "set_pin" if pin else "clear_pin", "shipment", shipment_id, {})
    return {"set": bool(pin), "ttl_hours": EDIT_TOKEN_TTL_HOURS}


@router.delete("/shipments/{shipment_id}")
async def delete_shipment(shipment_id: str, current_user: dict = Depends(require_admin)):
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    s["_deleted_from"] = "shipments"
    s["deleted_at"] = datetime.now(timezone.utc).isoformat()
    s["deleted_by"] = current_user["id"]
    await db.deleted_items.insert_one(s)
    await db.shipments.delete_one({"id": shipment_id})
    await _audit(current_user["id"], "delete", "shipment", shipment_id)
    return {"deleted": True}


@router.post("/shipments/{shipment_id}/rotate-token")
async def rotate_token(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Invalidate the current public link + issue a new one. Use when a token
    has been over-shared or compromised."""
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0, "id": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    new_token = secrets.token_urlsafe(20)
    await db.shipments.update_one({"id": shipment_id}, {"$set": {
        "token": new_token,
        "token_rotated_at": datetime.now(timezone.utc).isoformat(),
    }})
    await _audit(current_user["id"], "update", "shipment_token_rotate", shipment_id)
    return {"token": new_token, "share_path": f"/donate/shipment/{new_token}"}


# ============================================================
# Items (admin only)
# ============================================================

def _normalise_item(data: dict) -> dict:
    """Coerce + clamp item fields. Used by both create and bulk-import."""
    name = (data.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="item.name is required")
    priority = (data.get("priority") or "normal").lower()
    if priority not in VALID_PRIORITIES:
        priority = "normal"
    container_type = (data.get("container_type") or "container").lower()
    if container_type not in ("container", "pallet", "box", "tote"):
        container_type = "container"
    return {
        "id": f"sit_{uuid.uuid4().hex[:8]}",
        "name": name[:160],
        "category": (data.get("category") or "")[:60],
        "qty_needed": max(1, int(data.get("qty_needed") or 1)),
        "qty_acquired": max(0, int(data.get("qty_acquired") or 0)),
        "weight_kg": max(0, float(data.get("weight_kg") or 0)),
        "dims_cm": {
            "length": max(0, float((data.get("dims_cm") or {}).get("length") or 0)),
            "width": max(0, float((data.get("dims_cm") or {}).get("width") or 0)),
            "height": max(0, float((data.get("dims_cm") or {}).get("height") or 0)),
        },
        "photo_url": (data.get("photo_url") or "")[:500],
        # Multiple photos from the AI scanner — cover, back, spine, etc.
        "image_urls": [(u or "")[:500] for u in (data.get("image_urls") or []) if u],
        "value_usd": max(0, float(data.get("value_usd") or 0)),
        "notes": (data.get("notes") or "")[:500],
        "priority": priority,
        "pallet_id": data.get("pallet_id") or None,
        # Stacking: if `parent_id` points to another item, this item sits ON TOP
        # of that one. Otherwise it sits on its pallet (or on the container floor
        # when container_type=container).
        "parent_id": data.get("parent_id") or None,
        "container_type": container_type,
        # Barcode identifiers from the scanner — used for waybill + dedupe.
        "isbn": (data.get("isbn") or "")[:30],
        "upc": (data.get("upc") or "")[:30],
        "author": (data.get("author") or "")[:120],         # Books: author
        "publisher": (data.get("publisher") or "")[:120],
        # Audit fields — set when added via the PIN-gated public scanner
        "scanned_by_pin_hint": (data.get("scanned_by_pin_hint") or "")[:8],
        "scanned_at": data.get("scanned_at"),
        "ai_identified": bool(data.get("ai_identified", False)),
        # Position WITHIN the assigned pallet (cm from pallet's back-left
        # corner). Optional — admin can set via the form-based item editor.
        "x_cm": max(0, float(data.get("x_cm") or 0)),
        "y_cm": max(0, float(data.get("y_cm") or 0)),
        "z_cm": max(0, float(data.get("z_cm") or 0)),
        "donations": [],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }


@router.post("/shipments/{shipment_id}/items")
async def add_item(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    item = _normalise_item(data)
    return await _add_or_merge_item(shipment_id, item)


async def _add_or_merge_item(shipment_id: str, item: dict) -> dict:
    """Add an item, OR — if another item in this shipment has the same
    ISBN/UPC AND the same pallet placement — increment its qty_acquired
    instead of creating a near-duplicate row.

    Also annotates the response with `over_pledged: true` when the merged
    qty exceeds qty_needed so the UI can warn the packer.
    """
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0, "items": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    existing_items = s.get("items") or []
    # Dedupe key: same ISBN or same UPC AND same pallet+container_type
    # (so the same book on two different pallets stays as two rows).
    dedupe_id = None
    if item.get("isbn") or item.get("upc"):
        for it in existing_items:
            if it.get("pallet_id") != item.get("pallet_id"):
                continue
            if it.get("container_type") != item.get("container_type"):
                continue
            same_isbn = item.get("isbn") and it.get("isbn") == item["isbn"]
            same_upc = item.get("upc") and it.get("upc") == item["upc"]
            if same_isbn or same_upc:
                dedupe_id = it["id"]
                break
    if dedupe_id:
        # Increment qty + refresh photo if we have a new one
        new_qty_delta = max(1, int(item.get("qty_acquired") or 1))
        set_ops = {"items.$.updated_at": datetime.now(timezone.utc).isoformat()}
        if item.get("photo_url"):
            set_ops["items.$.photo_url"] = item["photo_url"]
        await db.shipments.update_one(
            {"id": shipment_id, "items.id": dedupe_id},
            {"$inc": {"items.$.qty_acquired": new_qty_delta}, "$set": set_ops},
        )
        # Re-read the merged item so we can report over-pledge status
        s2 = await db.shipments.find_one(
            {"id": shipment_id, "items.id": dedupe_id},
            {"_id": 0, "items.$": 1},
        )
        merged = (s2 or {}).get("items", [{}])[0]
        merged["merged"] = True
        merged["over_pledged"] = merged.get("qty_acquired", 0) > merged.get("qty_needed", 1)
        return merged
    # New row
    await db.shipments.update_one({"id": shipment_id}, {"$push": {"items": item}})
    item["over_pledged"] = item.get("qty_acquired", 0) > item.get("qty_needed", 1)
    return item


@router.put("/shipments/{shipment_id}/items/{item_id}")
async def update_item(shipment_id: str, item_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"name", "category", "qty_needed", "qty_acquired", "weight_kg",
               "dims_cm", "photo_url", "image_urls", "value_usd", "notes", "priority",
               "pallet_id", "parent_id", "container_type", "isbn", "upc",
               "author", "publisher", "ai_identified",
               "x_cm", "y_cm", "z_cm"}
    set_ops = {}
    for k, v in data.items():
        if k not in allowed:
            continue
        # Clamp numeric fields just like create
        if k in ("qty_needed",):
            set_ops[f"items.$.{k}"] = max(1, int(v or 1))
        elif k in ("qty_acquired",):
            set_ops[f"items.$.{k}"] = max(0, int(v or 0))
        elif k in ("weight_kg", "value_usd", "x_cm", "y_cm", "z_cm"):
            set_ops[f"items.$.{k}"] = max(0, float(v or 0))
        elif k == "priority":
            p = (v or "normal").lower()
            set_ops[f"items.$.{k}"] = p if p in VALID_PRIORITIES else "normal"
        else:
            set_ops[f"items.$.{k}"] = v
    set_ops["items.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": shipment_id, "items.id": item_id},
        {"$set": set_ops},
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"updated": True}


@router.delete("/shipments/{shipment_id}/items/{item_id}")
async def delete_item(shipment_id: str, item_id: str, current_user: dict = Depends(require_admin)):
    r = await db.shipments.update_one(
        {"id": shipment_id}, {"$pull": {"items": {"id": item_id}}}
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"deleted": True}


# ─── Item photo upload + link-to-size estimation ────────────────

from fastapi import UploadFile, File  # noqa: E402


@router.post("/shipments/{shipment_id}/items/{item_id}/photo")
async def upload_item_photo(
    shipment_id: str, item_id: str,
    file: UploadFile = File(...),
    current_user: dict = Depends(require_admin),
):
    """Upload a product photo for an item. Cloud-storage with disk fallback,
    same pattern as child-extras / receipts."""
    if not file.content_type or not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Photo must be an image")
    data = await file.read()
    if len(data) > 5 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="Photo must be under 5 MB")
    ext = (file.filename or "").rsplit(".", 1)[-1] if "." in (file.filename or "") else "jpg"
    unique = f"{shipment_id}-{item_id}-{uuid.uuid4().hex[:6]}.{ext}"
    file_url = None
    try:
        from storage import put_object
        result = put_object(f"shipment-items/{unique}", data, file.content_type)
        file_url = result.get("url", f"/api/storage/shipment-items/{unique}")
    except Exception as e:
        logger.warning(f"Cloud put failed, saving locally: {e}")
        import os as _os
        _os.makedirs("/app/backend/uploads/shipment-items", exist_ok=True)
        with open(f"/app/backend/uploads/shipment-items/{unique}", "wb") as fh:
            fh.write(data)
        file_url = f"/api/uploads/shipment-items/{unique}"
    await db.shipments.update_one(
        {"id": shipment_id, "items.id": item_id},
        {"$set": {"items.$.photo_url": file_url}},
    )
    return {"photo_url": file_url}


@router.post("/shipments/{shipment_id}/items/{item_id}/estimate-from-link")
async def estimate_item_from_link(shipment_id: str, item_id: str, data: dict, current_user: dict = Depends(require_admin)):
    """AI-estimate weight + dimensions from a product URL (Amazon, Walmart, etc.).

    Pulls the page title + first content image (best-effort, no fancy scraping)
    and asks Gemini-3-flash to estimate weight_kg + dims_cm + value_usd. Writes
    the estimate onto the item — operator can edit afterward if it's off.

    Body: { url: str }
    """
    url = (data.get("url") or "").strip()
    if not url.startswith("http"):
        raise HTTPException(status_code=400, detail="url must start with http/https")
    s = await db.shipments.find_one({"id": shipment_id, "items.id": item_id}, {"_id": 0, "items.$": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Item not found")
    item = s["items"][0]

    import os as _os
    api_key = _os.environ.get("EMERGENT_LLM_KEY", "")
    if not api_key:
        raise HTTPException(status_code=503, detail="AI estimation unavailable (no LLM key configured)")

    # Pull the page title + first image hint with a 6s timeout. Don't try to be
    # clever; just grab whatever's in <title>, <meta og:image>, <meta og:title>.
    title_hint = ""
    image_hint = ""
    try:
        import httpx
        async with httpx.AsyncClient(timeout=6, follow_redirects=True, headers={"User-Agent": "Mozilla/5.0 (compatible; 5812Connect/1.0)"}) as client:
            r = await client.get(url)
            html = (r.text or "")[:50000]
            import re
            m = re.search(r'<title[^>]*>([^<]+)</title>', html, re.I)
            if m:
                title_hint = m.group(1).strip()[:300]
            m = re.search(r'<meta[^>]*property=[\"\']og:image[\"\'][^>]*content=[\"\']([^\"\']+)', html, re.I)
            if m:
                image_hint = m.group(1).strip()[:500]
            if not title_hint:
                m = re.search(r'<meta[^>]*property=[\"\']og:title[\"\'][^>]*content=[\"\']([^\"\']+)', html, re.I)
                if m:
                    title_hint = m.group(1).strip()[:300]
    except Exception as e:
        logger.warning(f"link fetch failed: {e}")

    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"AI client unavailable: {e}")
    sys_msg = (
        "You estimate physical dimensions, weight, and US dollar value for a product. "
        "Output STRICT JSON: {\"weight_kg\": float, \"dims_cm\": {\"length\": float, \"width\": float, \"height\": float}, "
        "\"value_usd\": float, \"confidence\": \"high\"|\"medium\"|\"low\", \"reasoning\": str (≤120 chars)}\n"
        "Use the product NAME + URL TITLE HINT to identify the item, then estimate per typical retail-packaging dimensions. "
        "If you can't identify the product confidently, set confidence=low and use conservative round-number defaults."
    )
    chat = LlmChat(
        api_key=api_key,
        session_id=f"shipment_estimate_{item_id}_{uuid.uuid4().hex[:6]}",
        system_message=sys_msg,
    ).with_model("gemini", "gemini-3-flash-preview")
    user_text = (
        f"Item name: {item.get('name', '')}\n"
        f"Category: {item.get('category', '')}\n"
        f"Product URL: {url}\n"
        f"Page title hint: {title_hint or '(could not fetch)'}\n"
        f"OG image hint: {image_hint or '(none)'}\n"
        "Estimate the per-unit weight, dimensions, and USD value."
    )
    raw = await chat.send_message(UserMessage(text=user_text))
    s_text = (raw or "").strip()
    if s_text.startswith("```"):
        s_text = s_text.strip("`")
        if s_text.lower().startswith("json"):
            s_text = s_text[4:].strip()
    first, last = s_text.find("{"), s_text.rfind("}")
    if first >= 0 and last > first:
        s_text = s_text[first:last + 1]
    import json as _json
    try:
        parsed = _json.loads(s_text)
    except Exception:
        raise HTTPException(status_code=502, detail="AI returned an unparseable response — please fill in dimensions manually")
    weight = max(0.0, float(parsed.get("weight_kg") or 0))
    dims = parsed.get("dims_cm") or {}
    dims_cm = {
        "length": max(0.0, float(dims.get("length") or 0)),
        "width": max(0.0, float(dims.get("width") or 0)),
        "height": max(0.0, float(dims.get("height") or 0)),
    }
    value = max(0.0, float(parsed.get("value_usd") or 0))
    set_ops = {
        "items.$.weight_kg": weight,
        "items.$.dims_cm": dims_cm,
        "items.$.value_usd": value,
        "items.$.source_url": url,
        "items.$.ai_estimate": {
            "confidence": (parsed.get("confidence") or "medium").lower(),
            "reasoning": (parsed.get("reasoning") or "")[:200],
            "estimated_at": datetime.now(timezone.utc).isoformat(),
        },
    }
    await db.shipments.update_one(
        {"id": shipment_id, "items.id": item_id},
        {"$set": set_ops},
    )
    return {
        "weight_kg": weight, "dims_cm": dims_cm, "value_usd": value,
        "confidence": (parsed.get("confidence") or "medium").lower(),
        "reasoning": parsed.get("reasoning") or "",
    }


@router.post("/shipments/{shipment_id}/items/bulk-import")
async def bulk_import_items(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    """Body: { items: [{name, qty_needed, weight_kg, ...}] }. Skips rows with no name."""
    rows = data.get("items") or []
    if not isinstance(rows, list):
        raise HTTPException(status_code=400, detail="items must be a list")
    items = []
    for r in rows:
        if not (r.get("name") or "").strip():
            continue
        try:
            items.append(_normalise_item(r))
        except HTTPException:
            continue
    if items:
        await db.shipments.update_one({"id": shipment_id}, {"$push": {"items": {"$each": items}}})
    return {"imported": len(items)}


# ============================================================
# Pallets (admin only)
# ============================================================

def _normalise_pallet(data: dict) -> dict:
    """Coerce + clamp pallet fields. Used by add and update."""
    label = (data.get("label") or "").strip() or f"Pallet {datetime.now(timezone.utc).strftime('%H%M%S')}"
    return {
        "id": f"plt_{uuid.uuid4().hex[:8]}",
        "label": label[:60],
        "notes": (data.get("notes") or "")[:300],
        # Physical pallet dims (cm). Default = standard EUR pallet 120×80×15cm
        # the height field represents the stack height (so a "tall pallet stack"
        # can be e.g. 150 cm tall once items are stacked on it).
        "length_cm": max(10, float(data.get("length_cm") or 120)),
        "width_cm":  max(10, float(data.get("width_cm")  or 80)),
        "height_cm": max(5,  float(data.get("height_cm") or 150)),
        # Position within the container floor (cm from the back-left interior
        # corner). 0,0 = back-left. Used by the 2D visualizer for placement.
        "x_cm": max(0, float(data.get("x_cm") or 0)),
        "y_cm": max(0, float(data.get("y_cm") or 0)),
        "color": (data.get("color") or "")[:16],   # optional hex tag e.g. "#10b981"
        "created_at": datetime.now(timezone.utc).isoformat(),
    }


@router.post("/shipments/{shipment_id}/pallets")
async def add_pallet(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    pallet = _normalise_pallet(data)
    r = await db.shipments.update_one({"id": shipment_id}, {"$push": {"pallets": pallet}})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return pallet


@router.put("/shipments/{shipment_id}/pallets/{pallet_id}")
async def update_pallet(shipment_id: str, pallet_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"label", "notes", "length_cm", "width_cm", "height_cm", "x_cm", "y_cm", "color"}
    set_ops = {}
    for k, v in data.items():
        if k not in allowed:
            continue
        if k in ("length_cm", "width_cm", "height_cm"):
            set_ops[f"pallets.$.{k}"] = max(5, float(v or 0))
        elif k in ("x_cm", "y_cm"):
            set_ops[f"pallets.$.{k}"] = max(0, float(v or 0))
        else:
            set_ops[f"pallets.$.{k}"] = v
    if not set_ops:
        return {"updated": False}
    set_ops["pallets.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": shipment_id, "pallets.id": pallet_id}, {"$set": set_ops}
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"updated": True}


@router.delete("/shipments/{shipment_id}/pallets/{pallet_id}")
async def delete_pallet(shipment_id: str, pallet_id: str, current_user: dict = Depends(require_admin)):
    # Also un-assign any items pointing at this pallet so they fall back to "unassigned"
    await db.shipments.update_one(
        {"id": shipment_id, "items.pallet_id": pallet_id},
        {"$set": {"items.$[el].pallet_id": None}},
        array_filters=[{"el.pallet_id": pallet_id}],
    )
    r = await db.shipments.update_one(
        {"id": shipment_id}, {"$pull": {"pallets": {"id": pallet_id}}}
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"deleted": True}


# ============================================================
# AI Packing — Gemini-generated text scenarios
# ============================================================

@router.post("/shipments/{shipment_id}/ai-packing")
async def generate_packing_scenario(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Generates a text packing scenario via Gemini-3-flash. Looks at the
    acquired items + pallets + 40' container dimensions and outputs a step-by-
    step plan: which pallets go where, total weight vs the cap, recommended
    grouping of remaining loose items, and any over-cap warnings.

    Persisted on the shipment doc so the FE can render it without re-spending
    tokens on every page load. Caller re-runs after material item changes.
    """
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    import os as _os
    api_key = _os.environ.get("EMERGENT_LLM_KEY", "")
    if not api_key:
        raise HTTPException(status_code=503, detail="AI packing unavailable (no LLM key configured)")
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"AI client unavailable: {e}")

    acquired = [i for i in (s.get("items") or []) if int(i.get("qty_acquired") or 0) > 0]
    total_weight = sum(float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0) for i in acquired)
    cap = float(s.get("max_payload_kg") or 26000)
    over_cap = total_weight - cap

    # Compact, structured prompt so the model has everything it needs without
    # token-bloat from raw donation history.
    payload = {
        "shipment_name": s.get("name"),
        "dest_country": s.get("dest_country"),
        "container_internal_cm": s.get("container_dims_cm") or CONTAINER_40FT_HC,
        "max_payload_kg": cap,
        "current_total_weight_kg": round(total_weight, 1),
        "over_cap_kg": round(over_cap, 1),
        "pallets": [{"id": p["id"], "label": p["label"]} for p in (s.get("pallets") or [])],
        "items_acquired": [
            {
                "id": i["id"], "name": i["name"], "category": i.get("category", ""),
                "qty_acquired": i.get("qty_acquired", 0),
                "weight_kg_per_unit": i.get("weight_kg", 0),
                "dims_cm": i.get("dims_cm") or {},
                "pallet_id": i.get("pallet_id"),
                "priority": i.get("priority", "normal"),
                "value_usd": i.get("value_usd", 0),
            }
            for i in acquired
        ][:200],  # cap to keep prompt under Gemini's window
    }
    system = (
        "You are a shipping/logistics assistant for a 58:12 Global container shipment to Uganda. "
        "Given the JSON state below, output a CONCISE packing scenario in Markdown with these sections:\n"
        "## Weight summary\n"
        "  • State current acquired weight vs the 40' container payload cap; flag any over-cap by ≥500 kg.\n"
        "## Volume reality check\n"
        "  • Estimate volume usage given the 40' HC internal ~76 m³. Note any items missing dimensions.\n"
        "## Pallet plan\n"
        "  • For each existing pallet, list which items belong on it (group by category + priority).\n"
        "  • Suggest names for any new pallets needed.\n"
        "  • Place heavy/dense pallets at the bottom-front of the container; lighter ones on top.\n"
        "## Loading order\n"
        "  • Numbered 1..N — back-of-container first, door-side last.\n"
        "## Risks & recommendations\n"
        "  • Call out fragility (electronics, glass), cold-chain (medical), and bulk-density issues.\n"
        "Keep it under 700 words. No prose preamble; jump straight into the headings."
    )
    chat = LlmChat(
        api_key=api_key,
        session_id=f"shipment_pack_{shipment_id}_{uuid.uuid4().hex[:6]}",
        system_message=system,
    ).with_model("gemini", "gemini-3-flash-preview")
    import json as _json
    text = await chat.send_message(UserMessage(text=_json.dumps(payload, default=str)))
    ai_text = (text or "").strip()
    await db.shipments.update_one({"id": shipment_id}, {"$set": {
        "ai_packing_text": ai_text,
        "ai_packing_generated_at": datetime.now(timezone.utc).isoformat(),
        "ai_packing_total_weight_kg": round(total_weight, 1),
    }})
    return {
        "text": ai_text,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_weight_kg": round(total_weight, 1),
        "over_cap_kg": round(over_cap, 1),
    }


# ============================================================
# PUBLIC — read + mark-as-donated (no auth)
# ============================================================

@router.get("/public/shipments/{token}")
async def public_shipment(token: str):
    """Public view — anyone with the token sees the wishlist. Returns the
    items + pallets but NOT the admin metadata (no created_by, no donor lists)."""
    s = await db.shipments.find_one({"token": token}, {"_id": 0})
    if not s or s.get("status") == "cancelled":
        raise HTTPException(status_code=404, detail="Shipment not found")
    items = s.get("items") or []
    still_needed = []
    already_acquired = []
    for i in items:
        # Sanitise — strip the donation log from the public payload (donor names
        # may be sensitive). Show the running counts only.
        snap = {k: v for k, v in i.items() if k not in ("donations", "created_at", "updated_at")}
        snap["qty_remaining"] = max(0, int(i.get("qty_needed") or 0) - int(i.get("qty_acquired") or 0))
        if snap["qty_remaining"] > 0:
            still_needed.append(snap)
        else:
            already_acquired.append(snap)
    # Sort still-needed by priority (urgent → low), then name
    pri_rank = {"urgent": 0, "high": 1, "normal": 2, "low": 3}
    still_needed.sort(key=lambda x: (pri_rank.get(x.get("priority", "normal"), 2), x.get("name", "").lower()))
    already_acquired.sort(key=lambda x: x.get("name", "").lower())

    total_weight = sum(float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0) for i in items)
    total_value = sum(float(i.get("value_usd") or 0) * int(i.get("qty_acquired") or 0) for i in items)
    cap = float(s.get("max_payload_kg") or 26000)
    # Lightweight pallet roster (INCLUDING dims + positions so the visualizer
    # can render boxes to scale + label them).
    pallets_lite = [{
        "id": p.get("id"), "label": p.get("label"),
        "length_cm": p.get("length_cm") or 120,
        "width_cm":  p.get("width_cm")  or 80,
        "height_cm": p.get("height_cm") or 150,
        "x_cm": p.get("x_cm") or 0,
        "y_cm": p.get("y_cm") or 0,
        "color": p.get("color") or "",
    } for p in (s.get("pallets") or [])]
    # Donor leaderboard (top 5 by total qty donated, anonymous excluded)
    donor_totals: dict[str, int] = {}
    donor_set = set()
    for it in items:
        for d in (it.get("donations") or []):
            name = (d.get("donor_name") or "Anonymous").strip() or "Anonymous"
            donor_set.add(name)
            if name.lower() != "anonymous":
                donor_totals[name] = donor_totals.get(name, 0) + int(d.get("qty") or 0)
    leaderboard = sorted(
        [{"donor_name": n, "total_qty": q} for n, q in donor_totals.items()],
        key=lambda x: x["total_qty"], reverse=True,
    )[:5]
    return {
        "id": s["id"],
        "name": s.get("name"),
        "dest_country": s.get("dest_country"),
        "description": s.get("description"),
        "target_ship_date": s.get("target_ship_date"),
        "status": s.get("status"),
        "max_payload_kg": cap,
        "container_dims_cm": s.get("container_dims_cm") or CONTAINER_40FT_HC,
        "still_needed": still_needed,
        "already_acquired": already_acquired,
        "pallets": pallets_lite,
        "totals": {
            "weight_kg": round(total_weight, 1),
            "weight_pct": round(min(100, (total_weight / cap) * 100), 1) if cap else 0,
            "value_usd": round(total_value, 2),
            "items_needed": len(still_needed),
            "items_acquired": len(already_acquired),
            "pallet_count": len(pallets_lite),
            "donor_count": len(donor_set),
            "leaderboard": leaderboard,
        },
        "ai_packing_text": s.get("ai_packing_text") or "",
        "ai_packing_generated_at": s.get("ai_packing_generated_at"),
        "pin_required": bool(s.get("access_pin_hash")),
    }


@router.post("/public/shipments/{token}/items/{item_id}/donate")
async def public_donate(token: str, item_id: str, data: dict):
    """Anyone with the token marks an item as (partially) donated.
    Body: { qty: int, donor_name?: str (no email required) }
    Idempotency: each call appends to the donations log AND increments
    qty_acquired. No "undo donate" from the public side — that requires admin.
    """
    qty = int(data.get("qty") or 0)
    if qty <= 0:
        raise HTTPException(status_code=400, detail="qty must be positive")
    donor_name = (data.get("donor_name") or "Anonymous").strip()[:60] or "Anonymous"
    s = await db.shipments.find_one({"token": token, "items.id": item_id}, {"_id": 0, "id": 1, "items.$": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Item not found on this shipment")
    item = (s.get("items") or [None])[0]
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    remaining = max(0, int(item.get("qty_needed") or 0) - int(item.get("qty_acquired") or 0))
    if qty > remaining:
        qty = remaining          # silently clamp — donor can't over-pledge past what's needed
    if qty <= 0:
        return {"item_id": item_id, "qty_recorded": 0, "message": "This item is already fully covered."}
    donation = {
        "id": f"don_{uuid.uuid4().hex[:8]}",
        "qty": qty,
        "donor_name": donor_name,
        "at": datetime.now(timezone.utc).isoformat(),
    }
    await db.shipments.update_one(
        {"id": s["id"], "items.id": item_id},
        {
            "$inc": {"items.$.qty_acquired": qty},
            "$push": {"items.$.donations": donation},
        },
    )
    return {
        "item_id": item_id, "qty_recorded": qty, "donor_name": donor_name,
        "message": f"Thank you{', ' + donor_name if donor_name != 'Anonymous' else ''}!",
    }


# ============================================================
# Public PIN login + scoped-edit endpoints
# These let trusted non-admin volunteers log in with a shipment-specific PIN
# and manage that ONE shipment's manifest. Pure subset of the admin endpoints.
# ============================================================

@router.post("/public/shipments/{token}/login")
async def public_login(token: str, data: dict):
    """Trade a PIN for an edit_token (valid 12h). 401 if PIN doesn't match."""
    pin = (data.get("pin") or "").strip()
    if not pin:
        raise HTTPException(status_code=400, detail="PIN required")
    s = await db.shipments.find_one(
        {"token": token}, {"_id": 0, "id": 1, "access_pin_hash": 1, "status": 1},
    )
    if not s or s.get("status") == "cancelled":
        raise HTTPException(status_code=404, detail="Shipment not found")
    if not s.get("access_pin_hash"):
        raise HTTPException(status_code=403, detail="No PIN is set on this shipment. Ask the admin to set one.")
    if not hmac.compare_digest(s["access_pin_hash"], _hash_pin(pin)):
        raise HTTPException(status_code=401, detail="Incorrect PIN")
    return {
        "edit_token": _make_edit_token(s["id"]),
        "ttl_hours": EDIT_TOKEN_TTL_HOURS,
        "shipment_id": s["id"],
    }


@router.put("/public/shipments/{token}/container")
async def public_update_container(token: str, data: dict, request: Request):
    """Editor: change container dimensions + max payload."""
    ctx = await require_shipment_editor(request, token)
    c = data or {}
    container = {
        "length_cm": max(50, float(c.get("length_cm") or CONTAINER_40FT_HC["length_cm"])),
        "width_cm":  max(50, float(c.get("width_cm")  or CONTAINER_40FT_HC["width_cm"])),
        "height_cm": max(50, float(c.get("height_cm") or CONTAINER_40FT_HC["height_cm"])),
        "max_payload_kg": float(c.get("max_payload_kg") or CONTAINER_40FT_HC["max_payload_kg"]),
    }
    await db.shipments.update_one(
        {"id": ctx["shipment_id"]},
        {"$set": {
            "container_dims_cm": container,
            "max_payload_kg": container["max_payload_kg"],
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }},
    )
    return {"updated": True, "container_dims_cm": container}


@router.post("/public/shipments/{token}/items")
async def public_add_item(token: str, data: dict, request: Request):
    """Editor: add an item to this shipment. Items with the same ISBN/UPC on
    the same pallet are merged (qty_acquired incremented) instead of duplicated."""
    ctx = await require_shipment_editor(request, token)
    item = _normalise_item(data)
    return await _add_or_merge_item(ctx["shipment_id"], item)


@router.put("/public/shipments/{token}/items/{item_id}")
async def public_update_item(token: str, item_id: str, data: dict, request: Request):
    """Editor: edit any item field (name, dims, weight, pallet_id, position)."""
    ctx = await require_shipment_editor(request, token)
    allowed = {"name", "category", "qty_needed", "qty_acquired", "weight_kg",
               "dims_cm", "photo_url", "image_urls", "value_usd", "notes", "priority",
               "pallet_id", "parent_id", "container_type", "isbn", "upc",
               "author", "publisher", "ai_identified",
               "x_cm", "y_cm", "z_cm"}
    set_ops = {}
    for k, v in data.items():
        if k not in allowed:
            continue
        if k in ("qty_needed",):
            set_ops[f"items.$.{k}"] = max(1, int(v or 1))
        elif k in ("qty_acquired",):
            set_ops[f"items.$.{k}"] = max(0, int(v or 0))
        elif k in ("weight_kg", "value_usd", "x_cm", "y_cm", "z_cm"):
            set_ops[f"items.$.{k}"] = max(0, float(v or 0))
        elif k == "priority":
            p = (v or "normal").lower()
            set_ops[f"items.$.{k}"] = p if p in VALID_PRIORITIES else "normal"
        else:
            set_ops[f"items.$.{k}"] = v
    set_ops["items.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": ctx["shipment_id"], "items.id": item_id},
        {"$set": set_ops},
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"updated": True}


@router.delete("/public/shipments/{token}/items/{item_id}")
async def public_delete_item(token: str, item_id: str, request: Request):
    ctx = await require_shipment_editor(request, token)
    r = await db.shipments.update_one(
        {"id": ctx["shipment_id"]}, {"$pull": {"items": {"id": item_id}}},
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"deleted": True}


@router.post("/public/shipments/{token}/pallets")
async def public_add_pallet(token: str, data: dict, request: Request):
    ctx = await require_shipment_editor(request, token)
    pallet = _normalise_pallet(data)
    await db.shipments.update_one({"id": ctx["shipment_id"]}, {"$push": {"pallets": pallet}})
    return pallet


@router.put("/public/shipments/{token}/pallets/{pallet_id}")
async def public_update_pallet(token: str, pallet_id: str, data: dict, request: Request):
    ctx = await require_shipment_editor(request, token)
    allowed = {"label", "notes", "length_cm", "width_cm", "height_cm", "x_cm", "y_cm", "color"}
    set_ops = {}
    for k, v in data.items():
        if k not in allowed:
            continue
        if k in ("length_cm", "width_cm", "height_cm"):
            set_ops[f"pallets.$.{k}"] = max(5, float(v or 0))
        elif k in ("x_cm", "y_cm"):
            set_ops[f"pallets.$.{k}"] = max(0, float(v or 0))
        else:
            set_ops[f"pallets.$.{k}"] = v
    if not set_ops:
        return {"updated": False}
    set_ops["pallets.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": ctx["shipment_id"], "pallets.id": pallet_id},
        {"$set": set_ops},
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"updated": True}


@router.delete("/public/shipments/{token}/pallets/{pallet_id}")
async def public_delete_pallet(token: str, pallet_id: str, request: Request):
    ctx = await require_shipment_editor(request, token)
    await db.shipments.update_one(
        {"id": ctx["shipment_id"], "items.pallet_id": pallet_id},
        {"$set": {"items.$[el].pallet_id": None}},
        array_filters=[{"el.pallet_id": pallet_id}],
    )
    r = await db.shipments.update_one(
        {"id": ctx["shipment_id"]}, {"$pull": {"pallets": {"id": pallet_id}}},
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"deleted": True}



# ============================================================
# AI ITEM SCANNER — public, PIN-gated
# ============================================================
# Volunteers logged in via the donor PIN can take 1–3 photos of an item (book
# cover/back/spine, barcode, or general shot) and the AI identifies the title /
# author / ISBN / UPC / category. If the photo contained a barcode, we hit
# external catalogues (Google Books for ISBNs, OpenFoodFacts for UPCs) to fill
# in canonical metadata before returning to the client.

@router.post("/public/shipments/{token}/scan-item")
async def public_scan_item(
    token: str,
    request: Request,
    images: List[UploadFile] = File(default=[]),
    isbn: Optional[str] = None,
    upc: Optional[str] = None,
):
    """Identify a shipment item from up to 3 photos and/or a scanned barcode.

    Returns a candidate item dict (NOT yet persisted) — the volunteer reviews,
    edits, then POSTs to /items to actually add it to the shipment.
    """
    ctx = await require_shipment_editor(request, token)
    pin_hint = (ctx.get("pin_used") or "")[-4:] if ctx.get("pin_used") else ""

    # Sanity: at least one signal must be present
    if not images and not isbn and not upc:
        raise HTTPException(status_code=400, detail="Provide at least one image, ISBN, or UPC")

    # 1) Try external catalogues first — they're definitive when we have a barcode
    enriched: dict = {}
    if isbn:
        try:
            import httpx
            async with httpx.AsyncClient(timeout=6) as cli:
                r = await cli.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{isbn.strip()}")
                if r.status_code == 200:
                    js = r.json()
                    if js.get("totalItems", 0) > 0:
                        v = js["items"][0]["volumeInfo"]
                        enriched = {
                            "name": v.get("title") or "",
                            "author": ", ".join(v.get("authors") or []),
                            "publisher": v.get("publisher") or "",
                            "category": (v.get("categories") or ["Books"])[0],
                            "isbn": isbn.strip(),
                            "photo_url": ((v.get("imageLinks") or {}).get("thumbnail") or "").replace("http://", "https://"),
                            "weight_kg": 0.3,    # typical paperback
                            "dims_cm": {"length": 20, "width": 13, "height": 2},
                            "value_usd": float(((js["items"][0].get("saleInfo") or {}).get("listPrice") or {}).get("amount") or 12.0),
                            "ai_identified": False,
                            "source": "google_books",
                        }
        except Exception as e:
            logger.warning(f"google books lookup failed: {e}")

    if upc and not enriched:
        try:
            import httpx
            async with httpx.AsyncClient(timeout=6) as cli:
                r = await cli.get(f"https://world.openfoodfacts.org/api/v2/product/{upc.strip()}.json")
                if r.status_code == 200:
                    js = r.json()
                    if js.get("status") == 1:
                        p = js.get("product") or {}
                        enriched = {
                            "name": p.get("product_name") or p.get("generic_name") or "",
                            "category": (p.get("categories", "").split(",") or ["Food"])[0].strip()[:60],
                            "upc": upc.strip(),
                            "photo_url": p.get("image_front_url") or "",
                            "weight_kg": 0.5,
                            "dims_cm": {"length": 10, "width": 10, "height": 20},
                            "value_usd": 4.0,
                            "ai_identified": False,
                            "source": "openfoodfacts",
                        }
        except Exception as e:
            logger.warning(f"openfoodfacts lookup failed: {e}")

    # 2) If still empty (no barcode hit), invoke AI vision with the photos
    image_urls: List[str] = []
    if images:
        # Persist photos for audit + so the waybill can reference them later
        for img in images[:3]:
            data = await img.read()
            if not data or len(data) > 8_000_000:
                continue
            from routers.shipments import _persist_shipment_image  # type: ignore
            try:
                url = await _persist_shipment_image(ctx["shipment_id"], data, img.content_type or "image/jpeg")
                image_urls.append(url)
            except Exception:
                pass

    if not enriched and image_urls:
        api_key = _os.environ.get("EMERGENT_LLM_KEY", "")
        if api_key:
            try:
                from emergentintegrations.llm.chat import LlmChat, UserMessage, FileContentWithMimeType
                # Pull the first image back into a temp file for the AI
                import tempfile
                import httpx as _httpx
                async with _httpx.AsyncClient(timeout=10) as cli:
                    rr = await cli.get(image_urls[0])
                    img_bytes = rr.content
                fd, tmp = tempfile.mkstemp(suffix=".jpg")
                with _os.fdopen(fd, "wb") as fh:
                    fh.write(img_bytes)
                sys_msg = (
                    "You identify physical items from photos for a charity shipment inventory. "
                    "Read any barcodes, ISBNs, titles, or text on the item. Output STRICT JSON: "
                    "{\"name\": str, \"category\": str (one of: Books, Clothing, Food, Toys, Medical, Electronics, Household, Stationery, Other), "
                    "\"author\": str, \"publisher\": str, \"isbn\": str, \"upc\": str, "
                    "\"weight_kg\": float, \"dims_cm\": {\"length\": float, \"width\": float, \"height\": float}, "
                    "\"value_usd\": float, \"confidence\": \"high\"|\"medium\"|\"low\"}. "
                    "Empty string for unknown fields. Round-number conservative estimates for dims/weight/value."
                )
                # Primary: Gemini 3 Flash
                chat = LlmChat(
                    api_key=api_key,
                    session_id=f"shipment_scan_{uuid.uuid4().hex[:6]}",
                    system_message=sys_msg,
                ).with_model("gemini", "gemini-3-flash-preview")
                msg = UserMessage(
                    text="Identify this item. Read barcodes / ISBNs / titles. Return strict JSON.",
                    file_contents=[FileContentWithMimeType(file_path=tmp, mime_type="image/jpeg")],
                )
                raw = await chat.send_message(msg)
                s = (raw or "").strip()
                if s.startswith("```"):
                    s = s.strip("`")
                    if s.lower().startswith("json"):
                        s = s[4:].strip()
                first, last = s.find("{"), s.rfind("}")
                if first >= 0 and last > first:
                    s = s[first:last + 1]
                import json as _json
                parsed = _json.loads(s)
                confidence = (parsed.get("confidence") or "low").lower()
                # GPT-4o fallback if Gemini was low confidence
                if confidence == "low":
                    chat2 = LlmChat(
                        api_key=api_key,
                        session_id=f"shipment_scan_gpt_{uuid.uuid4().hex[:6]}",
                        system_message=sys_msg,
                    ).with_model("openai", "gpt-4o")
                    raw2 = await chat2.send_message(msg)
                    s2 = (raw2 or "").strip()
                    if s2.startswith("```"):
                        s2 = s2.strip("`")
                        if s2.lower().startswith("json"):
                            s2 = s2[4:].strip()
                    f2, l2 = s2.find("{"), s2.rfind("}")
                    if f2 >= 0 and l2 > f2:
                        parsed = _json.loads(s2[f2:l2 + 1])
                enriched = {
                    "name": parsed.get("name") or "",
                    "category": parsed.get("category") or "Other",
                    "author": parsed.get("author") or "",
                    "publisher": parsed.get("publisher") or "",
                    "isbn": parsed.get("isbn") or "",
                    "upc": parsed.get("upc") or "",
                    "weight_kg": float(parsed.get("weight_kg") or 0.5),
                    "dims_cm": parsed.get("dims_cm") or {"length": 20, "width": 13, "height": 5},
                    "value_usd": float(parsed.get("value_usd") or 5.0),
                    "ai_identified": True,
                    "ai_confidence": parsed.get("confidence") or "low",
                    "source": "ai_vision",
                }
                # If AI extracted an ISBN, try one more time to enrich via Google Books
                if parsed.get("isbn") and not enriched.get("publisher"):
                    try:
                        async with _httpx.AsyncClient(timeout=4) as cli:
                            gr = await cli.get(f"https://www.googleapis.com/books/v1/volumes?q=isbn:{parsed['isbn']}")
                            if gr.status_code == 200 and gr.json().get("totalItems", 0) > 0:
                                v = gr.json()["items"][0]["volumeInfo"]
                                enriched["publisher"] = v.get("publisher") or enriched["publisher"]
                                enriched["author"] = ", ".join(v.get("authors") or []) or enriched["author"]
                    except Exception:
                        pass
                try:
                    _os.remove(tmp)
                except Exception:
                    pass
            except Exception as e:
                logger.warning(f"AI scan failed: {e}")

    # 3) Final shape — always returns SOMETHING the client can show + edit
    if not enriched:
        enriched = {
            "name": "Unidentified item",
            "category": "Other",
            "ai_identified": False,
            "ai_confidence": "low",
            "source": "manual",
            "weight_kg": 0.5,
            "dims_cm": {"length": 20, "width": 20, "height": 10},
            "value_usd": 5.0,
        }
    enriched["image_urls"] = image_urls
    enriched["photo_url"] = enriched.get("photo_url") or (image_urls[0] if image_urls else "")
    enriched["scanned_by_pin_hint"] = pin_hint
    enriched["scanned_at"] = datetime.now(timezone.utc).isoformat()
    return enriched


async def _persist_shipment_image(shipment_id: str, data: bytes, mime: str) -> str:
    """Persist a scanned-item photo and return a URL. Cloud storage with
    on-disk fallback — same pattern as item-photo upload."""
    ext = (mime.split("/")[-1] if "/" in mime else "jpg")
    name = f"shipments/{shipment_id}/scans/{uuid.uuid4().hex}.{ext}"
    try:
        from storage import upload_bytes      # type: ignore
        return await upload_bytes(name, data, mime)
    except Exception:
        pass
    # Disk fallback
    import os as _o
    base = "/app/backend/uploads/shipments"
    _o.makedirs(base, exist_ok=True)
    p = f"{base}/{uuid.uuid4().hex}.{ext}"
    with open(p, "wb") as fh:
        fh.write(data)
    return f"/uploads/shipments/{_o.path.basename(p)}"


# ============================================================
# WAYBILL — printable manifest for a shipment
# ============================================================

def _waybill_html(s: dict) -> str:
    """Render an HTML waybill. Used both for the printable preview AND as the
    source for the PDF route below."""
    items = s.get("items") or []
    pallets = s.get("pallets") or []
    total_value = sum((it.get("value_usd") or 0) * (it.get("qty_acquired") or 1) for it in items)
    total_weight = sum((it.get("weight_kg") or 0) * (it.get("qty_acquired") or 1) for it in items)
    by_pallet: dict = {None: []}
    for p in pallets:
        by_pallet[p["id"]] = []
    for it in items:
        by_pallet.setdefault(it.get("pallet_id"), []).append(it)

    rows = []
    for p in pallets:
        rows.append(f"<tr style='background:#eef;'><td colspan=7><strong>Pallet {p.get('label') or p['id'][:6]}</strong> · {p.get('dims_cm', {}).get('length', 100)}×{p.get('dims_cm', {}).get('width', 80)}×{p.get('dims_cm', {}).get('height', 15)} cm</td></tr>")
        for it in by_pallet.get(p["id"], []):
            rows.append(
                f"<tr><td>{it.get('name', '')}</td>"
                f"<td>{it.get('category', '')}</td>"
                f"<td>{it.get('isbn') or it.get('upc') or ''}</td>"
                f"<td>{it.get('qty_acquired', 1)}</td>"
                f"<td>${(it.get('value_usd') or 0):.2f}</td>"
                f"<td>{(it.get('weight_kg') or 0):.2f} kg</td>"
                f"<td>{p.get('label') or p['id'][:6]}</td></tr>"
            )
    # Unassigned items
    if by_pallet.get(None):
        rows.append("<tr style='background:#fee;'><td colspan=7><strong>Loose (no pallet)</strong></td></tr>")
        for it in by_pallet.get(None, []):
            rows.append(
                f"<tr><td>{it.get('name', '')}</td>"
                f"<td>{it.get('category', '')}</td>"
                f"<td>{it.get('isbn') or it.get('upc') or ''}</td>"
                f"<td>{it.get('qty_acquired', 1)}</td>"
                f"<td>${(it.get('value_usd') or 0):.2f}</td>"
                f"<td>{(it.get('weight_kg') or 0):.2f} kg</td>"
                f"<td>—</td></tr>"
            )

    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>Waybill — {s.get('name', '')}</title>
<style>
body {{ font-family: Inter, system-ui, sans-serif; margin: 24px; color: #111; }}
h1 {{ margin-bottom: 4px; }}
.subtitle {{ color: #555; margin-bottom: 16px; font-size: 13px; }}
table {{ border-collapse: collapse; width: 100%; font-size: 12px; }}
th, td {{ border: 1px solid #ddd; padding: 6px 8px; text-align: left; }}
th {{ background: #fafafa; }}
.totals {{ margin-top: 18px; font-size: 13px; }}
.totals strong {{ display: inline-block; min-width: 140px; }}
</style></head><body>
<h1>Waybill / Manifest</h1>
<p class="subtitle">{s.get('name', 'Untitled shipment')} · {len(items)} items · {len(pallets)} pallets · Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</p>
<p class="subtitle"><strong>Origin:</strong> {s.get('origin', '—')} · <strong>Destination:</strong> {s.get('destination', '—')} · <strong>Ship date:</strong> {s.get('ship_date') or '—'}</p>
<table>
<thead><tr><th>Item</th><th>Category</th><th>ISBN / UPC</th><th>Qty</th><th>Unit value</th><th>Weight</th><th>Pallet</th></tr></thead>
<tbody>{''.join(rows)}</tbody>
</table>
<div class="totals">
<p><strong>Total items:</strong> {sum((it.get('qty_acquired') or 1) for it in items)}</p>
<p><strong>Total value:</strong> ${total_value:.2f}</p>
<p><strong>Total weight:</strong> {total_weight:.2f} kg</p>
</div>
</body></html>"""


@router.get("/shipments/{shipment_id}/waybill")
async def waybill_html(shipment_id: str, current_user: dict = Depends(require_admin)):
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return Response(content=_waybill_html(s), media_type="text/html")


@router.get("/public/shipments/{token}/waybill")
async def public_waybill_html(token: str, request: Request):
    """Public PIN-gated waybill. Editor token accepted either via the
    X-Shipment-Edit-Token header (XHR/fetch) or as ?edit_token=... in the URL
    (so `window.open()` can pop it in a new tab for printing)."""
    ctx = await require_shipment_editor(request, token)
    s = await db.shipments.find_one({"id": ctx["shipment_id"]}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return Response(content=_waybill_html(s), media_type="text/html")
