"""Shipment Tracker — 40' container collection + packing.

Admins (and only admins) manage a shipment. Anyone with the shareable token can:
  • view the wishlist (still needed + already acquired)
  • mark items as donated, optionally with a donor name (no auth, no email)
  • watch the running shipment weight + 40' container cap

AI packing scenarios are generated by Gemini-3-flash from the live item/pallet
state — text-only, fits inside a Markdown box on both the admin + public UIs.

40' high-cube container reference:
  Internal:  12.03 m × 2.35 m × 2.69 m   (≈ 76 m³)
  Max payload: ~26,000 kg
"""
from fastapi import APIRouter, Depends, HTTPException
from deps import db, get_current_user, _audit, require_admin, logger
from datetime import datetime, timezone
from typing import Optional
import uuid
import secrets

router = APIRouter(prefix="/api", tags=["shipments"])

# 40' high-cube interior dimensions in cm — used in the AI packing prompt.
CONTAINER_40FT_HC = {"length_cm": 1203, "width_cm": 235, "height_cm": 269, "max_payload_kg": 26000}

VALID_PRIORITIES = {"low", "normal", "high", "urgent"}
VALID_STATUSES = {"planning", "collecting", "packed", "shipped", "delivered", "cancelled"}


# ============================================================
# Admin CRUD (require_admin)
# ============================================================

@router.get("/shipments")
async def list_shipments(current_user: dict = Depends(require_admin)):
    """All shipments. Newest first. Sponsor-token NOT included in the list view
    to avoid accidentally leaking tokens into screenshots — fetch the detail
    endpoint to get the token + share URL."""
    rows = await db.shipments.find({}, {"_id": 0, "token": 0}).sort("created_at", -1).to_list(500)
    # Lightweight rollup so the list shows progress at-a-glance
    for s in rows:
        items = s.get("items") or []
        s["item_count"] = len(items)
        s["total_needed"] = sum(int(i.get("qty_needed") or 0) for i in items)
        s["total_acquired"] = sum(int(i.get("qty_acquired") or 0) for i in items)
        s["total_weight_kg"] = round(sum(
            (float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0)) for i in items
        ), 1)
        # Drop heavy nested arrays from the list payload
        s.pop("items", None)
        s.pop("pallets", None)
    return rows


@router.post("/shipments")
async def create_shipment(data: dict, current_user: dict = Depends(require_admin)):
    name = (data.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="name is required")
    token = secrets.token_urlsafe(20)  # ~26-char URL-safe random
    doc = {
        "id": f"sh_{uuid.uuid4().hex[:10]}",
        "token": token,
        "name": name[:120],
        "dest_country": (data.get("dest_country") or "Uganda")[:60],
        "description": (data.get("description") or "")[:1000],
        "target_ship_date": (data.get("target_ship_date") or "")[:10],
        "status": "planning",
        "max_payload_kg": float(data.get("max_payload_kg") or CONTAINER_40FT_HC["max_payload_kg"]),
        "container_dims_cm": CONTAINER_40FT_HC,
        "items": [],
        "pallets": [],
        "ai_packing_text": "",
        "ai_packing_generated_at": None,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "created_by": current_user["id"],
        "created_by_name": current_user.get("name", ""),
    }
    await db.shipments.insert_one(doc)
    doc.pop("_id", None)
    await _audit(current_user["id"], "create", "shipment", doc["id"], {"name": name})
    return doc


@router.get("/shipments/{shipment_id}")
async def get_shipment(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Full shipment detail INCLUDING the token + the share URL — only admins
    see this. Public visitors use the /api/public/shipments/{token} path."""
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    # Build a share URL hint — the FE will format it with REACT_APP_BACKEND_URL → site root
    s["share_path"] = f"/donate/shipment/{s.get('token', '')}"
    return s


@router.put("/shipments/{shipment_id}")
async def update_shipment(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"name", "dest_country", "description", "target_ship_date", "status", "max_payload_kg"}
    update = {k: v for k, v in data.items() if k in allowed}
    if "status" in update and update["status"] not in VALID_STATUSES:
        raise HTTPException(status_code=400, detail=f"status must be one of {sorted(VALID_STATUSES)}")
    update["updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one({"id": shipment_id}, {"$set": update})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return await db.shipments.find_one({"id": shipment_id}, {"_id": 0})


@router.delete("/shipments/{shipment_id}")
async def delete_shipment(shipment_id: str, current_user: dict = Depends(require_admin)):
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    s["_deleted_from"] = "shipments"
    s["deleted_at"] = datetime.now(timezone.utc).isoformat()
    s["deleted_by"] = current_user["id"]
    await db.deleted_items.insert_one(s)
    await db.shipments.delete_one({"id": shipment_id})
    await _audit(current_user["id"], "delete", "shipment", shipment_id)
    return {"deleted": True}


@router.post("/shipments/{shipment_id}/rotate-token")
async def rotate_token(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Invalidate the current public link + issue a new one. Use when a token
    has been over-shared or compromised."""
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0, "id": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    new_token = secrets.token_urlsafe(20)
    await db.shipments.update_one({"id": shipment_id}, {"$set": {
        "token": new_token,
        "token_rotated_at": datetime.now(timezone.utc).isoformat(),
    }})
    await _audit(current_user["id"], "update", "shipment_token_rotate", shipment_id)
    return {"token": new_token, "share_path": f"/donate/shipment/{new_token}"}


# ============================================================
# Items (admin only)
# ============================================================

def _normalise_item(data: dict) -> dict:
    """Coerce + clamp item fields. Used by both create and bulk-import."""
    name = (data.get("name") or "").strip()
    if not name:
        raise HTTPException(status_code=400, detail="item.name is required")
    priority = (data.get("priority") or "normal").lower()
    if priority not in VALID_PRIORITIES:
        priority = "normal"
    return {
        "id": f"sit_{uuid.uuid4().hex[:8]}",
        "name": name[:160],
        "category": (data.get("category") or "")[:60],
        "qty_needed": max(1, int(data.get("qty_needed") or 1)),
        "qty_acquired": max(0, int(data.get("qty_acquired") or 0)),
        "weight_kg": max(0, float(data.get("weight_kg") or 0)),
        "dims_cm": {
            "length": max(0, float((data.get("dims_cm") or {}).get("length") or 0)),
            "width": max(0, float((data.get("dims_cm") or {}).get("width") or 0)),
            "height": max(0, float((data.get("dims_cm") or {}).get("height") or 0)),
        },
        "photo_url": (data.get("photo_url") or "")[:500],
        "value_usd": max(0, float(data.get("value_usd") or 0)),
        "notes": (data.get("notes") or "")[:500],
        "priority": priority,
        "pallet_id": data.get("pallet_id") or None,
        "donations": [],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }


@router.post("/shipments/{shipment_id}/items")
async def add_item(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    item = _normalise_item(data)
    r = await db.shipments.update_one({"id": shipment_id}, {"$push": {"items": item}})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return item


@router.put("/shipments/{shipment_id}/items/{item_id}")
async def update_item(shipment_id: str, item_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"name", "category", "qty_needed", "qty_acquired", "weight_kg",
               "dims_cm", "photo_url", "value_usd", "notes", "priority", "pallet_id"}
    set_ops = {}
    for k, v in data.items():
        if k not in allowed:
            continue
        # Clamp numeric fields just like create
        if k in ("qty_needed",):
            set_ops[f"items.$.{k}"] = max(1, int(v or 1))
        elif k in ("qty_acquired",):
            set_ops[f"items.$.{k}"] = max(0, int(v or 0))
        elif k in ("weight_kg", "value_usd"):
            set_ops[f"items.$.{k}"] = max(0, float(v or 0))
        elif k == "priority":
            p = (v or "normal").lower()
            set_ops[f"items.$.{k}"] = p if p in VALID_PRIORITIES else "normal"
        else:
            set_ops[f"items.$.{k}"] = v
    set_ops["items.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": shipment_id, "items.id": item_id},
        {"$set": set_ops},
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"updated": True}


@router.delete("/shipments/{shipment_id}/items/{item_id}")
async def delete_item(shipment_id: str, item_id: str, current_user: dict = Depends(require_admin)):
    r = await db.shipments.update_one(
        {"id": shipment_id}, {"$pull": {"items": {"id": item_id}}}
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Item not found")
    return {"deleted": True}


@router.post("/shipments/{shipment_id}/items/bulk-import")
async def bulk_import_items(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    """Body: { items: [{name, qty_needed, weight_kg, ...}] }. Skips rows with no name."""
    rows = data.get("items") or []
    if not isinstance(rows, list):
        raise HTTPException(status_code=400, detail="items must be a list")
    items = []
    for r in rows:
        if not (r.get("name") or "").strip():
            continue
        try:
            items.append(_normalise_item(r))
        except HTTPException:
            continue
    if items:
        await db.shipments.update_one({"id": shipment_id}, {"$push": {"items": {"$each": items}}})
    return {"imported": len(items)}


# ============================================================
# Pallets (admin only)
# ============================================================

@router.post("/shipments/{shipment_id}/pallets")
async def add_pallet(shipment_id: str, data: dict, current_user: dict = Depends(require_admin)):
    label = (data.get("label") or "").strip() or f"Pallet {datetime.now(timezone.utc).strftime('%H%M%S')}"
    pallet = {
        "id": f"plt_{uuid.uuid4().hex[:8]}",
        "label": label[:60],
        "notes": (data.get("notes") or "")[:300],
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    r = await db.shipments.update_one({"id": shipment_id}, {"$push": {"pallets": pallet}})
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Shipment not found")
    return pallet


@router.put("/shipments/{shipment_id}/pallets/{pallet_id}")
async def update_pallet(shipment_id: str, pallet_id: str, data: dict, current_user: dict = Depends(require_admin)):
    allowed = {"label", "notes"}
    set_ops = {f"pallets.$.{k}": v for k, v in data.items() if k in allowed}
    if not set_ops:
        return {"updated": False}
    set_ops["pallets.$.updated_at"] = datetime.now(timezone.utc).isoformat()
    r = await db.shipments.update_one(
        {"id": shipment_id, "pallets.id": pallet_id}, {"$set": set_ops}
    )
    if r.matched_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"updated": True}


@router.delete("/shipments/{shipment_id}/pallets/{pallet_id}")
async def delete_pallet(shipment_id: str, pallet_id: str, current_user: dict = Depends(require_admin)):
    # Also un-assign any items pointing at this pallet so they fall back to "unassigned"
    await db.shipments.update_one(
        {"id": shipment_id, "items.pallet_id": pallet_id},
        {"$set": {"items.$[el].pallet_id": None}},
        array_filters=[{"el.pallet_id": pallet_id}],
    )
    r = await db.shipments.update_one(
        {"id": shipment_id}, {"$pull": {"pallets": {"id": pallet_id}}}
    )
    if r.modified_count == 0:
        raise HTTPException(status_code=404, detail="Pallet not found")
    return {"deleted": True}


# ============================================================
# AI Packing — Gemini-generated text scenarios
# ============================================================

@router.post("/shipments/{shipment_id}/ai-packing")
async def generate_packing_scenario(shipment_id: str, current_user: dict = Depends(require_admin)):
    """Generates a text packing scenario via Gemini-3-flash. Looks at the
    acquired items + pallets + 40' container dimensions and outputs a step-by-
    step plan: which pallets go where, total weight vs the cap, recommended
    grouping of remaining loose items, and any over-cap warnings.

    Persisted on the shipment doc so the FE can render it without re-spending
    tokens on every page load. Caller re-runs after material item changes.
    """
    s = await db.shipments.find_one({"id": shipment_id}, {"_id": 0})
    if not s:
        raise HTTPException(status_code=404, detail="Shipment not found")
    import os as _os
    api_key = _os.environ.get("EMERGENT_LLM_KEY", "")
    if not api_key:
        raise HTTPException(status_code=503, detail="AI packing unavailable (no LLM key configured)")
    try:
        from emergentintegrations.llm.chat import LlmChat, UserMessage
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"AI client unavailable: {e}")

    acquired = [i for i in (s.get("items") or []) if int(i.get("qty_acquired") or 0) > 0]
    total_weight = sum(float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0) for i in acquired)
    cap = float(s.get("max_payload_kg") or 26000)
    over_cap = total_weight - cap

    # Compact, structured prompt so the model has everything it needs without
    # token-bloat from raw donation history.
    payload = {
        "shipment_name": s.get("name"),
        "dest_country": s.get("dest_country"),
        "container_internal_cm": s.get("container_dims_cm") or CONTAINER_40FT_HC,
        "max_payload_kg": cap,
        "current_total_weight_kg": round(total_weight, 1),
        "over_cap_kg": round(over_cap, 1),
        "pallets": [{"id": p["id"], "label": p["label"]} for p in (s.get("pallets") or [])],
        "items_acquired": [
            {
                "id": i["id"], "name": i["name"], "category": i.get("category", ""),
                "qty_acquired": i.get("qty_acquired", 0),
                "weight_kg_per_unit": i.get("weight_kg", 0),
                "dims_cm": i.get("dims_cm") or {},
                "pallet_id": i.get("pallet_id"),
                "priority": i.get("priority", "normal"),
                "value_usd": i.get("value_usd", 0),
            }
            for i in acquired
        ][:200],  # cap to keep prompt under Gemini's window
    }
    system = (
        "You are a shipping/logistics assistant for a 58:12 Global container shipment to Uganda. "
        "Given the JSON state below, output a CONCISE packing scenario in Markdown with these sections:\n"
        "## Weight summary\n"
        "  • State current acquired weight vs the 40' container payload cap; flag any over-cap by ≥500 kg.\n"
        "## Volume reality check\n"
        "  • Estimate volume usage given the 40' HC internal ~76 m³. Note any items missing dimensions.\n"
        "## Pallet plan\n"
        "  • For each existing pallet, list which items belong on it (group by category + priority).\n"
        "  • Suggest names for any new pallets needed.\n"
        "  • Place heavy/dense pallets at the bottom-front of the container; lighter ones on top.\n"
        "## Loading order\n"
        "  • Numbered 1..N — back-of-container first, door-side last.\n"
        "## Risks & recommendations\n"
        "  • Call out fragility (electronics, glass), cold-chain (medical), and bulk-density issues.\n"
        "Keep it under 700 words. No prose preamble; jump straight into the headings."
    )
    chat = LlmChat(
        api_key=api_key,
        session_id=f"shipment_pack_{shipment_id}_{uuid.uuid4().hex[:6]}",
        system_message=system,
    ).with_model("gemini", "gemini-3-flash-preview")
    import json as _json
    text = await chat.send_message(UserMessage(text=_json.dumps(payload, default=str)))
    ai_text = (text or "").strip()
    await db.shipments.update_one({"id": shipment_id}, {"$set": {
        "ai_packing_text": ai_text,
        "ai_packing_generated_at": datetime.now(timezone.utc).isoformat(),
        "ai_packing_total_weight_kg": round(total_weight, 1),
    }})
    return {
        "text": ai_text,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_weight_kg": round(total_weight, 1),
        "over_cap_kg": round(over_cap, 1),
    }


# ============================================================
# PUBLIC — read + mark-as-donated (no auth)
# ============================================================

@router.get("/public/shipments/{token}")
async def public_shipment(token: str):
    """Public view — anyone with the token sees the wishlist. Returns the
    items + pallets but NOT the admin metadata (no created_by, no donor lists)."""
    s = await db.shipments.find_one({"token": token}, {"_id": 0})
    if not s or s.get("status") == "cancelled":
        raise HTTPException(status_code=404, detail="Shipment not found")
    items = s.get("items") or []
    still_needed = []
    already_acquired = []
    for i in items:
        # Sanitise — strip the donation log from the public payload (donor names
        # may be sensitive). Show the running counts only.
        snap = {k: v for k, v in i.items() if k not in ("donations", "created_at", "updated_at")}
        snap["qty_remaining"] = max(0, int(i.get("qty_needed") or 0) - int(i.get("qty_acquired") or 0))
        if snap["qty_remaining"] > 0:
            still_needed.append(snap)
        else:
            already_acquired.append(snap)
    # Sort still-needed by priority (urgent → low), then name
    pri_rank = {"urgent": 0, "high": 1, "normal": 2, "low": 3}
    still_needed.sort(key=lambda x: (pri_rank.get(x.get("priority", "normal"), 2), x.get("name", "").lower()))
    already_acquired.sort(key=lambda x: x.get("name", "").lower())

    total_weight = sum(float(i.get("weight_kg") or 0) * int(i.get("qty_acquired") or 0) for i in items)
    total_value = sum(float(i.get("value_usd") or 0) * int(i.get("qty_acquired") or 0) for i in items)
    cap = float(s.get("max_payload_kg") or 26000)
    return {
        "id": s["id"],
        "name": s.get("name"),
        "dest_country": s.get("dest_country"),
        "description": s.get("description"),
        "target_ship_date": s.get("target_ship_date"),
        "status": s.get("status"),
        "max_payload_kg": cap,
        "still_needed": still_needed,
        "already_acquired": already_acquired,
        "totals": {
            "weight_kg": round(total_weight, 1),
            "weight_pct": round(min(100, (total_weight / cap) * 100), 1) if cap else 0,
            "value_usd": round(total_value, 2),
            "items_needed": len(still_needed),
            "items_acquired": len(already_acquired),
        },
        "ai_packing_text": s.get("ai_packing_text") or "",
        "ai_packing_generated_at": s.get("ai_packing_generated_at"),
    }


@router.post("/public/shipments/{token}/items/{item_id}/donate")
async def public_donate(token: str, item_id: str, data: dict):
    """Anyone with the token marks an item as (partially) donated.
    Body: { qty: int, donor_name?: str (no email required) }
    Idempotency: each call appends to the donations log AND increments
    qty_acquired. No "undo donate" from the public side — that requires admin.
    """
    qty = int(data.get("qty") or 0)
    if qty <= 0:
        raise HTTPException(status_code=400, detail="qty must be positive")
    donor_name = (data.get("donor_name") or "Anonymous").strip()[:60] or "Anonymous"
    s = await db.shipments.find_one({"token": token, "items.id": item_id}, {"_id": 0, "id": 1, "items.$": 1})
    if not s:
        raise HTTPException(status_code=404, detail="Item not found on this shipment")
    item = (s.get("items") or [None])[0]
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    remaining = max(0, int(item.get("qty_needed") or 0) - int(item.get("qty_acquired") or 0))
    if qty > remaining:
        qty = remaining          # silently clamp — donor can't over-pledge past what's needed
    if qty <= 0:
        return {"item_id": item_id, "qty_recorded": 0, "message": "This item is already fully covered."}
    donation = {
        "id": f"don_{uuid.uuid4().hex[:8]}",
        "qty": qty,
        "donor_name": donor_name,
        "at": datetime.now(timezone.utc).isoformat(),
    }
    await db.shipments.update_one(
        {"id": s["id"], "items.id": item_id},
        {
            "$inc": {"items.$.qty_acquired": qty},
            "$push": {"items.$.donations": donation},
        },
    )
    return {
        "item_id": item_id, "qty_recorded": qty, "donor_name": donor_name,
        "message": f"Thank you{', ' + donor_name if donor_name != 'Anonymous' else ''}!",
    }
