"""Social Work Review Forms — School Progress + Welfare Home Visit.

Captures everything the paper forms 58:12 currently use collect:
  • Academic ratings, attendance/discipline, social-emotional, teacher comments,
    per-review action plan, overall progress rating  → "school_progress"
  • Welfare indicators, education/health/protection checks, household assessment,
    child's voice, strengths, challenges, action plan  → "welfare_visit"

Each saved form:
  1. Persists as a document in db.social_review_forms keyed by child_id + date + kind.
  2. Auto-syncs structured fields back into the child profile
     (db.children.{education,medical,family,protection,welfare_*}) so the existing
     report generator and child detail page surface the latest assessment without
     extra wiring.
  3. Appends a one-line summary to the case timeline (db.case_notes).

Printable blank templates (PDF) are generated by /templates/{kind}.pdf so a
social worker can print, fill by hand during a sight/school visit, and either
type the data into the in-app form OR upload a scan of the filled paper.
"""
from fastapi import APIRouter, Depends, HTTPException, UploadFile, File
from fastapi.responses import Response
from deps import db, get_current_user, _audit, require_staff, logger
from datetime import datetime, timezone
from typing import Optional
import uuid

router = APIRouter(prefix="/api/social-work/reviews", tags=["social_work_reviews"])

VALID_KINDS = {"school_progress", "welfare_visit"}


# ============================================================
# CRUD on filled review forms
# ============================================================

@router.get("/children/{child_id}")
async def list_child_reviews(
    child_id: str,
    kind: Optional[str] = None,
    current_user: dict = Depends(require_staff),
):
    """Timeline of review forms filed for one child. Optional ?kind= filter."""
    query = {"child_id": child_id}
    if kind:
        if kind not in VALID_KINDS:
            raise HTTPException(status_code=400, detail="kind must be school_progress or welfare_visit")
        query["kind"] = kind
    rows = await db.social_review_forms.find(query, {"_id": 0}).sort("review_date", -1).to_list(500)
    return rows


@router.get("/{review_id}")
async def get_review(review_id: str, current_user: dict = Depends(require_staff)):
    rev = await db.social_review_forms.find_one({"id": review_id}, {"_id": 0})
    if not rev:
        raise HTTPException(status_code=404, detail="Review form not found")
    return rev


@router.post("/children/{child_id}")
async def create_review(child_id: str, data: dict, current_user: dict = Depends(require_staff)):
    """Submit a filled review form. Body matches the form schema (verbatim from
    the .docx templates) — see TEMPLATES_SPEC below for the exact keys.
    On save we ALSO push the relevant structured fields back into the child's
    profile so the existing report generator surfaces them without extra wiring.
    """
    kind = (data.get("kind") or "").strip()
    if kind not in VALID_KINDS:
        raise HTTPException(status_code=400, detail="kind must be school_progress or welfare_visit")
    child = await db.children.find_one({"id": child_id}, {"_id": 0, "id": 1, "name": 1, "family_id": 1, "location_id": 1})
    if not child:
        raise HTTPException(status_code=404, detail="Child not found")

    review_date = (data.get("review_date") or datetime.now(timezone.utc).date().isoformat())[:10]
    review_id = f"rev_{uuid.uuid4().hex[:10]}"
    doc = {
        "id": review_id,
        "child_id": child_id,
        "child_name": child.get("name", ""),
        "family_id": child.get("family_id"),
        "location_id": child.get("location_id"),
        "kind": kind,
        "review_date": review_date,
        "fields": data.get("fields") or {},   # the whole filled-out form body
        "action_plan": data.get("action_plan") or [],
        "overall_assessment": data.get("overall_assessment") or "",
        "social_worker_id": current_user["id"],
        "social_worker_name": current_user.get("name", ""),
        "term": data.get("term") or "",
        "next_visit_date": data.get("next_visit_date") or "",
        "attached_scan_url": data.get("attached_scan_url") or "",
        "status": "submitted",
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.social_review_forms.insert_one(doc)
    doc.pop("_id", None)

    # ---- Auto-sync into child profile ----
    await _apply_review_to_child(child_id, kind, data, current_user, review_id)

    # ---- Timeline note ----
    try:
        case = await db.social_cases.find_one({"subject_kind": "child", "subject_id": child_id, "status": "active"}, {"_id": 0, "id": 1})
        if case:
            summary = {
                "school_progress": f"School progress review filed — overall: {doc['overall_assessment'] or 'n/a'}",
                "welfare_visit": f"Home/welfare visit logged — overall: {doc['overall_assessment'] or 'n/a'}",
            }.get(kind, "Review form filed")
            await db.case_notes.insert_one({
                "id": f"note_{uuid.uuid4().hex[:8]}",
                "case_id": case["id"],
                "text": summary,
                "review_id": review_id,
                "created_by": current_user["id"],
                "created_by_name": current_user.get("name", ""),
                "created_at": datetime.now(timezone.utc).isoformat(),
            })
    except Exception as e:
        logger.warning(f"review timeline note failed: {e}")

    await _audit(current_user["id"], "create", "social_review", review_id, {"kind": kind, "child_id": child_id})
    return doc


@router.put("/{review_id}")
async def update_review(review_id: str, data: dict, current_user: dict = Depends(require_staff)):
    rev = await db.social_review_forms.find_one({"id": review_id}, {"_id": 0})
    if not rev:
        raise HTTPException(status_code=404, detail="Review form not found")
    allowed = {"fields", "action_plan", "overall_assessment", "term", "next_visit_date", "review_date", "attached_scan_url", "status"}
    update = {k: v for k, v in data.items() if k in allowed}
    update["updated_at"] = datetime.now(timezone.utc).isoformat()
    update["updated_by"] = current_user["id"]
    await db.social_review_forms.update_one({"id": review_id}, {"$set": update})
    fresh = await db.social_review_forms.find_one({"id": review_id}, {"_id": 0})
    # Re-apply to child profile since fields may have changed
    await _apply_review_to_child(rev["child_id"], rev["kind"], {**rev, **update}, current_user, review_id)
    return fresh


@router.delete("/{review_id}")
async def delete_review(review_id: str, current_user: dict = Depends(require_staff)):
    rev = await db.social_review_forms.find_one({"id": review_id}, {"_id": 0})
    if not rev:
        raise HTTPException(status_code=404, detail="Review form not found")
    rev["_deleted_from"] = "social_review_forms"
    rev["deleted_at"] = datetime.now(timezone.utc).isoformat()
    rev["deleted_by"] = current_user["id"]
    await db.deleted_items.insert_one(rev)
    await db.social_review_forms.delete_one({"id": review_id})
    return {"deleted": True}


# ============================================================
# Auto-sync filled review into child profile
# ============================================================

async def _apply_review_to_child(child_id: str, kind: str, data: dict, user: dict, review_id: str):
    """Pull structured indicators out of the form payload and merge them into
    the child's profile so the existing report-pdf endpoint surfaces them
    without any extra logic on its side.

    Idempotent — runs on every save / update of the review.
    Updates done with $set so untouched fields are preserved.
    """
    fields = data.get("fields") or {}
    set_ops = {}

    if kind == "school_progress":
        # Education updates
        if fields.get("class_grade"):
            set_ops["education.grade"] = fields["class_grade"]
        if fields.get("school"):
            set_ops["education.school_name"] = fields["school"]
        if fields.get("term"):
            set_ops["education.current_term"] = fields["term"]
        # Latest ratings — store the whole block under education.latest_review for the
        # report generator to render verbatim.
        set_ops["education.latest_review"] = {
            "review_id": review_id,
            "review_date": data.get("review_date") or "",
            "academic_performance": fields.get("academic_performance") or {},
            "attendance_discipline": fields.get("attendance_discipline") or {},
            "social_emotional": fields.get("social_emotional") or {},
            "strengths": fields.get("strengths") or "",
            "areas_requiring_support": fields.get("areas_requiring_support") or "",
            "overall": data.get("overall_assessment") or "",
        }

    elif kind == "welfare_visit":
        # Family / Caregiver
        if fields.get("caregiver_name"):
            set_ops["family.primary_caregiver"] = fields["caregiver_name"]
        if fields.get("caregiver_relationship"):
            set_ops["family.caregiver_relationship"] = fields["caregiver_relationship"]
        if fields.get("village_parish"):
            set_ops["family.village_parish"] = fields["village_parish"]
        if fields.get("district"):
            set_ops["family.district"] = fields["district"]
        if fields.get("household") is not None:
            set_ops["family.household_assessment"] = fields["household"]
        # Welfare assessment block — store on a new `welfare` sub-doc that the
        # frontend Welfare tab + report PDF pick up.
        set_ops["welfare.latest_review"] = {
            "review_id": review_id,
            "review_date": data.get("review_date") or "",
            "indicators": fields.get("welfare_indicators") or {},
            "education_checks": fields.get("education_checks") or {},
            "health_nutrition": fields.get("health_nutrition") or {},
            "protection_concerns": fields.get("protection_concerns") or {},
            "protection_details": fields.get("protection_details") or "",
            "child_voice": fields.get("child_voice") or {},
            "strengths": fields.get("strengths") or "",
            "challenges": fields.get("challenges") or "",
            "overall": data.get("overall_assessment") or "",
            "next_visit_date": data.get("next_visit_date") or "",
        }
        # Protection alert flags — easy for kiosk / dashboard surfacing
        prot = fields.get("protection_concerns") or {}
        flag_keys = ["neglect", "physical_abuse", "emotional_abuse", "child_labour",
                     "school_dropout_risk", "early_marriage_risk", "other_protection"]
        any_flag = any(bool(prot.get(k)) for k in flag_keys)
        set_ops["protection.has_active_concern"] = any_flag
        set_ops["protection.flags"] = {k: bool(prot.get(k)) for k in flag_keys}
        set_ops["protection.last_assessed_at"] = data.get("review_date") or datetime.now(timezone.utc).date().isoformat()

    set_ops["updated_at"] = datetime.now(timezone.utc).isoformat()
    set_ops["last_review_id"] = review_id
    set_ops["last_review_at"] = datetime.now(timezone.utc).isoformat()
    if set_ops:
        await db.children.update_one({"id": child_id}, {"$set": set_ops})


# ============================================================
# Blank printable templates
# ============================================================

SCHOOL_REVIEW_BLANK_HTML = """<!DOCTYPE html><html><head><meta charset="utf-8"><title>School Progress Review</title>
<style>
body { font-family: Arial, sans-serif; padding: 36px 32px; color: #1a1a2e; font-size: 11pt; line-height: 1.45; }
.header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 10px; border-bottom: 3px solid #fbbf24; margin-bottom: 14px; }
.brand { font-size: 14pt; font-weight: 700; color: #1a1a2e; letter-spacing: 1px; }
.brand-sub { color: #fbbf24; font-size: 9pt; font-weight: 600; margin-top: 2px; }
.form-id { text-align: right; font-size: 9pt; color: #64748b; }
h1 { font-size: 16pt; text-align: center; margin: 12px 0 18px 0; text-transform: uppercase; letter-spacing: 1.5px; }
h2 { font-size: 11pt; margin: 16px 0 6px 0; background: #f1f5f9; padding: 6px 10px; border-left: 4px solid #fbbf24; }
.fld { display: flex; align-items: baseline; margin: 4px 0; }
.fld label { font-weight: 600; min-width: 130px; }
.fld .line { flex: 1; border-bottom: 1px dotted #334155; min-height: 18px; margin-left: 6px; }
.row2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
table { width: 100%; border-collapse: collapse; margin: 6px 0 8px 0; font-size: 10pt; }
th, td { border: 1px solid #94a3b8; padding: 6px 8px; vertical-align: top; }
th { background: #f8fafc; text-align: center; font-weight: 600; font-size: 9.5pt; }
.rating { width: 38px; text-align: center; }
.checkbox { display: inline-block; width: 11px; height: 11px; border: 1.2px solid #334155; vertical-align: middle; margin-right: 4px; }
.sig { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-top: 22px; }
.sig .slot { border-top: 1px solid #334155; padding-top: 4px; font-size: 9pt; }
.note { font-size: 8pt; color: #64748b; margin-top: 18px; text-align: center; }
</style></head>
<body>
<div class="header">
  <div><div class="brand">{{ORG_NAME}}</div><div class="brand-sub">Welfare &amp; Education Programme</div></div>
  <div class="form-id">Form: SP-REV-01<br/>Print date: {{TODAY}}</div>
</div>
<h1>Child School Progress Review</h1>

<h2>Child Information</h2>
<div class="row2">
  <div class="fld"><label>Child Name</label><span class="line"></span></div>
  <div class="fld"><label>Sponsorship ID</label><span class="line"></span></div>
  <div class="fld"><label>School</label><span class="line"></span></div>
  <div class="fld"><label>Class/Grade</label><span class="line"></span></div>
  <div class="fld"><label>Term</label><span class="line"></span></div>
  <div class="fld"><label>Review Date</label><span class="line"></span></div>
</div>

<h2>Academic Performance <span style="font-weight:400; font-size:9pt; color:#64748b;">(tick the appropriate column)</span></h2>
<table>
  <thead><tr><th style="text-align:left;">Area</th><th class="rating">Excellent</th><th class="rating">Good</th><th class="rating">Fair</th><th class="rating">Poor</th><th>Comments</th></tr></thead>
  <tbody>
    <tr><td>Overall academic performance</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Reading and writing skills</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Mathematics performance</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Class participation</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Attendance &amp; Discipline</h2>
<table>
  <thead><tr><th style="text-align:left;">Indicator</th><th class="rating">Yes</th><th class="rating">No</th><th>Comments</th></tr></thead>
  <tbody>
    <tr><td>Attends school regularly</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Arrives on time</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Demonstrates good discipline</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Completes assignments/homework</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Social and Emotional Development</h2>
<table>
  <thead><tr><th style="text-align:left;">Indicator</th><th class="rating">Good</th><th class="rating">Fair</th><th class="rating">Poor</th><th>Comments</th></tr></thead>
  <tbody>
    <tr><td>Relates well with peers</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Respects teachers and school rules</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Confidence and self-esteem</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Participation in co-curricular activities</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Teacher&rsquo;s Comments</h2>
<div class="fld"><label>Strengths</label><span class="line" style="min-height:32px;"></span></div>
<div class="fld"><label>Areas requiring support</label><span class="line" style="min-height:32px;"></span></div>

<h2>Action Plan</h2>
<table>
  <thead><tr><th style="width:24px;">No.</th><th>Identified Concern</th><th>Action Required</th><th>Responsible</th><th style="width:90px;">Timeline</th></tr></thead>
  <tbody>
    <tr><td>1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr><td>2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr><td>3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Overall Assessment <span style="font-weight:400; font-size:9pt; color:#64748b;">(tick one)</span></h2>
<p>
  <span class="checkbox"></span> Excellent Progress &nbsp;&nbsp;
  <span class="checkbox"></span> Good Progress &nbsp;&nbsp;
  <span class="checkbox"></span> Satisfactory Progress &nbsp;&nbsp;
  <span class="checkbox"></span> Needs Additional Support &nbsp;&nbsp;
  <span class="checkbox"></span> Requires Immediate Follow-up
</p>

<div class="sig">
  <div class="slot"><strong>Class Teacher</strong><br/>Name: _________________<br/>Sign &amp; Date: ________________</div>
  <div class="slot"><strong>Head Teacher</strong> (optional)<br/>Name: _________________<br/>Sign &amp; Date: ________________</div>
  <div class="slot"><strong>Social Worker</strong><br/>Name: _________________<br/>Sign &amp; Date: ________________</div>
</div>

<div class="note">{{ORG_NAME}} &middot; Confidential &mdash; for internal use only &middot; Form returns to the social worker for upload into the child&rsquo;s digital profile.</div>
</body></html>
"""


WELFARE_VISIT_BLANK_HTML = """<!DOCTYPE html><html><head><meta charset="utf-8"><title>Child Welfare Review &amp; Home Visit</title>
<style>
body { font-family: Arial, sans-serif; padding: 36px 32px; color: #1a1a2e; font-size: 11pt; line-height: 1.45; }
.header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 10px; border-bottom: 3px solid #fbbf24; margin-bottom: 14px; }
.brand { font-size: 14pt; font-weight: 700; color: #1a1a2e; letter-spacing: 1px; }
.brand-sub { color: #fbbf24; font-size: 9pt; font-weight: 600; margin-top: 2px; }
.form-id { text-align: right; font-size: 9pt; color: #64748b; }
h1 { font-size: 16pt; text-align: center; margin: 12px 0 18px 0; text-transform: uppercase; letter-spacing: 1.5px; }
h2 { font-size: 11pt; margin: 16px 0 6px 0; background: #f1f5f9; padding: 6px 10px; border-left: 4px solid #fbbf24; }
.fld { display: flex; align-items: baseline; margin: 4px 0; }
.fld label { font-weight: 600; min-width: 150px; }
.fld .line { flex: 1; border-bottom: 1px dotted #334155; min-height: 18px; margin-left: 6px; }
.row2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
table { width: 100%; border-collapse: collapse; margin: 6px 0 8px 0; font-size: 10pt; }
th, td { border: 1px solid #94a3b8; padding: 6px 8px; vertical-align: top; }
th { background: #f8fafc; text-align: center; font-weight: 600; font-size: 9.5pt; }
.rating { width: 38px; text-align: center; }
.checkbox { display: inline-block; width: 11px; height: 11px; border: 1.2px solid #334155; vertical-align: middle; margin-right: 4px; }
.sig { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 16px; margin-top: 22px; }
.sig .slot { border-top: 1px solid #334155; padding-top: 4px; font-size: 9pt; }
.note { font-size: 8pt; color: #64748b; margin-top: 18px; text-align: center; }
.checkrow { margin: 3px 0; font-size: 10pt; }
</style></head>
<body>
<div class="header">
  <div><div class="brand">{{ORG_NAME}}</div><div class="brand-sub">Welfare &amp; Education Programme</div></div>
  <div class="form-id">Form: WV-REV-01<br/>Print date: {{TODAY}}</div>
</div>
<h1>Child Welfare Review and Home Visit</h1>

<h2>Visit Details</h2>
<div class="row2">
  <div class="fld"><label>Date of Visit</label><span class="line"></span></div>
  <div class="fld"><label>Child Name</label><span class="line"></span></div>
  <div class="fld"><label>Sponsorship ID</label><span class="line"></span></div>
  <div class="fld"><label>Age</label><span class="line"></span></div>
  <div class="fld"><label>Sex</label><span class="line"></span></div>
  <div class="fld"><label>Caregiver Name</label><span class="line"></span></div>
  <div class="fld"><label>Relationship to Child</label><span class="line"></span></div>
  <div class="fld"><label>Village / Parish</label><span class="line"></span></div>
  <div class="fld"><label>District</label><span class="line"></span></div>
</div>

<h2>Child Welfare Assessment <span style="font-weight:400; font-size:9pt; color:#64748b;">(Good / Fair / Poor — tick one per row)</span></h2>
<table>
  <thead><tr><th style="text-align:left;">Welfare Indicator</th><th class="rating">Good</th><th class="rating">Fair</th><th class="rating">Poor</th><th>Comments</th></tr></thead>
  <tbody>
    <tr><td>Physical Health</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Nutrition Status</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Personal Hygiene</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Emotional / Psychological Well-being</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Safety and Protection</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>School Attendance</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Academic Progress</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Family Support and Care</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>Living Conditions</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Education Status</h2>
<div class="checkrow"><span class="checkbox"></span> Enrolled in school &nbsp;&nbsp; <span class="checkbox"></span> Attends regularly &nbsp;&nbsp; <span class="checkbox"></span> Adequate learning materials</div>
<div class="checkrow"><span class="checkbox"></span> School fees/scholastic needs met &nbsp;&nbsp; <span class="checkbox"></span> Progressing academically</div>

<h2>Health and Nutrition</h2>
<div class="checkrow"><span class="checkbox"></span> Appears healthy &nbsp;&nbsp; <span class="checkbox"></span> Accesses medical care when needed &nbsp;&nbsp; <span class="checkbox"></span> Receives adequate meals daily</div>
<div class="checkrow"><span class="checkbox"></span> Disability or chronic illness identified (specify below)</div>

<h2>Child Protection Concerns <span style="font-weight:400; font-size:9pt; color:#64748b;">(tick any that apply)</span></h2>
<div class="checkrow"><span class="checkbox"></span> Neglect &nbsp;&nbsp; <span class="checkbox"></span> Physical Abuse &nbsp;&nbsp; <span class="checkbox"></span> Emotional Abuse &nbsp;&nbsp; <span class="checkbox"></span> Child Labour</div>
<div class="checkrow"><span class="checkbox"></span> School Dropout Risk &nbsp;&nbsp; <span class="checkbox"></span> Early Marriage Risk &nbsp;&nbsp; <span class="checkbox"></span> Other Protection Concern</div>
<div class="fld" style="margin-top:6px;"><label>Details</label><span class="line" style="min-height:30px;"></span></div>

<h2>Household and Family Environment</h2>
<table>
  <thead><tr><th style="width:24px;">No.</th><th style="text-align:left;">Indicator</th><th class="rating">Good</th><th class="rating">Fair</th><th class="rating">Poor</th><th>Comments</th></tr></thead>
  <tbody>
    <tr><td>1</td><td>Caregiver-child relationship</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>2</td><td>Household stability</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>3</td><td>Housing condition</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>4</td><td>Water and sanitation facilities</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
    <tr><td>5</td><td>Family capacity to meet basic needs</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td class="rating">&#9744;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Child&rsquo;s Voice</h2>
<div class="fld"><label>What is going well at home/school?</label><span class="line" style="min-height:30px;"></span></div>
<div class="fld"><label>What challenges are you facing?</label><span class="line" style="min-height:30px;"></span></div>
<div class="fld"><label>What support would you like?</label><span class="line" style="min-height:30px;"></span></div>

<h2>Strengths and Positive Changes Observed</h2>
<div style="border-bottom:1px dotted #334155; min-height:42px;"></div>

<h2>Key Challenges Identified</h2>
<div style="border-bottom:1px dotted #334155; min-height:42px;"></div>

<h2>Agreed Action Plan</h2>
<table>
  <thead><tr><th style="width:24px;">No.</th><th>Identified Need</th><th>Action Required</th><th>Responsible</th><th style="width:90px;">Timeline</th></tr></thead>
  <tbody>
    <tr><td>1</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr><td>2</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr><td>3</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
    <tr><td>4</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr>
  </tbody>
</table>

<h2>Overall Case Assessment <span style="font-weight:400; font-size:9pt; color:#64748b;">(tick one)</span></h2>
<p>
  <span class="checkbox"></span> The child is thriving and progressing well &nbsp;&nbsp;
  <span class="checkbox"></span> Requires routine monitoring &nbsp;&nbsp;
  <span class="checkbox"></span> Requires additional support services &nbsp;&nbsp;
  <span class="checkbox"></span> Requires urgent intervention
</p>
<p><span class="checkbox"></span> Referral made to another service provider (specify)</p>

<div class="sig">
  <div class="slot"><strong>Caregiver</strong><br/>Name: _______________<br/>Sign &amp; Date: ________________</div>
  <div class="slot"><strong>Child</strong><br/>Name: _______________<br/>Sign &amp; Date: ________________</div>
  <div class="slot"><strong>Social Worker</strong><br/>Name: _______________<br/>Sign &amp; Date: ________________</div>
</div>

<p style="margin-top:14px; font-size:9pt;"><strong>Next Visit Date:</strong> ___________________</p>

<div class="note">{{ORG_NAME}} &middot; Confidential &mdash; for internal use only &middot; Form returns to the social worker for upload into the child&rsquo;s digital profile.</div>
</body></html>
"""


@router.get("/templates/{kind}.pdf")
async def download_blank_template(kind: str, current_user: dict = Depends(require_staff)):
    """Generate a printable blank template PDF for the social worker to take
    into the field. Branding (org name) is pulled from system_settings so each
    deployment gets its own header."""
    if kind not in VALID_KINDS:
        raise HTTPException(status_code=400, detail="kind must be school_progress or welfare_visit")
    org_name = "58:12 Global"
    try:
        settings = await db.system_settings.find_one({"id": "settings"}, {"_id": 0, "branding": 1, "org": 1})
        if settings:
            b = settings.get("branding") or {}
            o = settings.get("org") or {}
            org_name = b.get("app_name") or o.get("name") or org_name
    except Exception:
        pass
    today = datetime.now(timezone.utc).strftime("%d %b %Y")
    template = SCHOOL_REVIEW_BLANK_HTML if kind == "school_progress" else WELFARE_VISIT_BLANK_HTML
    html = template.replace("{{ORG_NAME}}", org_name).replace("{{TODAY}}", today)

    try:
        from weasyprint import HTML
        pdf_bytes = HTML(string=html).write_pdf()
        filename = "school-progress-review-blank.pdf" if kind == "school_progress" else "welfare-visit-blank.pdf"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
    except Exception as e:
        logger.warning(f"PDF generation failed, returning HTML: {e}")
        return Response(content=html.encode(), media_type="text/html")


# ============================================================
# Upload a scanned filled paper form (no OCR yet — just attaches the file)
# ============================================================

@router.post("/children/{child_id}/upload-scan")
async def upload_filled_scan(
    child_id: str,
    file: UploadFile = File(...),
    kind: str = "welfare_visit",
    review_date: Optional[str] = None,
    current_user: dict = Depends(require_staff),
):
    """Upload a scanned-and-filled paper form. Stored as a child_extra (kind='report')
    so it appears in the existing extras gallery, and a draft review-form row is
    created so staff can later transcribe the data in-app."""
    if kind not in VALID_KINDS:
        raise HTTPException(status_code=400, detail="kind must be school_progress or welfare_visit")
    if not file.content_type or not (file.content_type == "application/pdf" or file.content_type.startswith("image/")):
        raise HTTPException(status_code=400, detail="Scan must be a PDF or image")
    data = await file.read()
    if len(data) > 15 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="Scan must be under 15 MB")

    child = await db.children.find_one({"id": child_id}, {"_id": 0, "id": 1, "name": 1, "location_id": 1})
    if not child:
        raise HTTPException(status_code=404, detail="Child not found")

    ext = (file.filename or "").rsplit(".", 1)[-1] if "." in (file.filename or "") else "pdf"
    unique = f"{child_id}-{kind}-{uuid.uuid4().hex[:8]}.{ext}"
    file_url = None
    try:
        from storage import put_object
        result = put_object(f"social-review-scans/{unique}", data, file.content_type)
        file_url = result.get("url", f"/api/storage/social-review-scans/{unique}")
    except Exception as e:
        logger.warning(f"Cloud storage put failed, saving locally: {e}")
        import os
        os.makedirs("/app/backend/uploads/social-review-scans", exist_ok=True)
        with open(f"/app/backend/uploads/social-review-scans/{unique}", "wb") as fh:
            fh.write(data)
        file_url = f"/api/uploads/social-review-scans/{unique}"

    # Create a draft review-form row referencing the scan — staff transcribes later.
    review_id = f"rev_{uuid.uuid4().hex[:10]}"
    rdate = (review_date or datetime.now(timezone.utc).date().isoformat())[:10]
    rev = {
        "id": review_id,
        "child_id": child_id,
        "child_name": child.get("name", ""),
        "location_id": child.get("location_id"),
        "kind": kind,
        "review_date": rdate,
        "fields": {},
        "action_plan": [],
        "overall_assessment": "",
        "attached_scan_url": file_url,
        "status": "draft_scan_only",
        "social_worker_id": current_user["id"],
        "social_worker_name": current_user.get("name", ""),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.social_review_forms.insert_one(rev)
    rev.pop("_id", None)
    # Also store in the existing child_extras so the gallery surfaces it.
    try:
        await db.child_extras.insert_one({
            "id": f"cex_{uuid.uuid4().hex[:10]}",
            "child_id": child_id,
            "child_name": child.get("name"),
            "kind": "report",
            "caption": f"Filled {kind.replace('_', ' ')} form ({rdate})",
            "file_url": file_url,
            "file_name": file.filename,
            "is_public_for_sponsor": False,
            "location_id": child.get("location_id"),
            "review_id": review_id,
            "created_at": datetime.now(timezone.utc).isoformat(),
            "created_by": current_user["id"],
            "created_by_name": current_user.get("name", ""),
        })
    except Exception as e:
        logger.warning(f"child_extras mirror failed: {e}")
    await _audit(current_user["id"], "create", "social_review_scan", review_id, {"kind": kind, "child_id": child_id})
    return rev
