#!/usr/bin/env bash
# 58:12 Connect — one-line appliance installer.
#
# Usage on a fresh Ubuntu 22.04+ / Debian 12 / Raspberry Pi OS box:
#
#   curl -fsSL https://raw.githubusercontent.com/silvesterlubwama/5812Connect/5812/appliance/install.sh | sudo bash
#
# Or after cloning:
#
#   cd appliance && sudo bash install.sh
#
# What it does:
#   1. Installs Docker Engine + docker compose plugin (skipped if present).
#   2. Drops the appliance into /opt/connect (configurable).
#   3. Generates fresh JWT_SECRET and NFC_SECRET_KEY into .env (preserved on re-run).
#   4. Pulls the latest images from GHCR.
#   5. Brings the stack up + waits for /healthz.
#   6. Prints the LAN IP + URL.

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/connect}"
REPO="${CONNECT_REPO:-https://github.com/silvesterlubwama/5812Connect.git}"
BRANCH="${CONNECT_BRANCH:-5812}"

log()   { printf '\033[1;36m==> %s\033[0m\n' "$*"; }
warn()  { printf '\033[1;33m!! %s\033[0m\n' "$*"; }
err()   { printf '\033[1;31mxx %s\033[0m\n' "$*"; exit 1; }

[ "$(id -u)" = "0" ] || err "Run as root (use sudo)."

# ── 0. Bootstrap missing prerequisites ───────────────────────────
# Minimal Ubuntu Server / Pi OS / Debian images often ship without curl,
# git, or openssl. Install whatever's missing before we need it.
log "Checking for bootstrap prerequisites…"
needed=""
for cmd in curl git openssl ca-certificates; do
    case "$cmd" in
        ca-certificates) dpkg -s ca-certificates >/dev/null 2>&1 || needed="$needed ca-certificates" ;;
        *) command -v "$cmd" >/dev/null 2>&1 || needed="$needed $cmd" ;;
    esac
done
if [ -n "$needed" ]; then
    log "Installing:$needed"
    if command -v apt-get >/dev/null 2>&1; then
        apt-get update -qq
        apt-get install -y --no-install-recommends $needed
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y $needed
    elif command -v yum >/dev/null 2>&1; then
        yum install -y $needed
    else
        err "No apt-get / dnf / yum found. Install$needed manually and re-run."
    fi
fi

# ── 1. Docker ────────────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
    log "Installing Docker Engine + compose plugin…"
    curl -fsSL https://get.docker.com | sh
else
    log "Docker already installed — $(docker --version)"
fi

if ! docker compose version >/dev/null 2>&1; then
    err "docker compose plugin missing. Re-run get.docker.com or install manually."
fi

# ── 2. Source ────────────────────────────────────────────────────
if [ ! -d "$INSTALL_DIR/.git" ]; then
    log "Cloning $REPO@$BRANCH → $INSTALL_DIR"
    git clone --branch "$BRANCH" --depth 1 "$REPO" "$INSTALL_DIR"
else
    log "Updating existing checkout in $INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch origin "$BRANCH"
    git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH"
fi

APPLIANCE="$INSTALL_DIR/appliance"
cd "$APPLIANCE"

# ── 3. .env ──────────────────────────────────────────────────────
if [ ! -f .env ]; then
    log "Generating fresh .env (secrets randomised) — edit before production use."
    JWT=$(openssl rand -hex 48)
    NFC=$(openssl rand -hex 32)
    # Write .env directly so we don't depend on .env.example existing in the
    # checkout (some early commits accidentally gitignored it).
    cat > .env <<EOF
# ─────────────────────────────────────────────────────────────────
# 58:12 Connect appliance — runtime configuration.
# Auto-generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit values below as needed and re-run \`docker compose up -d\` to apply.
# ─────────────────────────────────────────────────────────────────

# Required — random secrets baked in at install time
JWT_SECRET=$JWT
NFC_SECRET_KEY=$NFC

# Database
DB_NAME=connect

# Public hostname + TLS (leave SITE_DOMAIN blank for LAN-only)
SITE_DOMAIN=
ACME_EMAIL=admin@example.org

# Remote access via Cloudflare Tunnel (optional)
CLOUDFLARED_TOKEN=
# Uncomment to auto-spawn the tunnel on \`docker compose up\`:
# COMPOSE_PROFILES=tunnel

# Email integration (optional — admin can also paste in /admin UI)
RESEND_API_KEY=
SENDER_EMAIL=

# AI / OCR integration (optional)
EMERGENT_LLM_KEY=

# Web Push notifications (optional)
VAPID_PRIVATE_KEY=
VAPID_EMAIL=

# Error tracking (optional)
SENTRY_DSN=

# Image overrides — for self-built or pinned versions
# BACKEND_IMAGE=ghcr.io/silvesterlubwama/connect-backend:v0.1.0
# FRONTEND_IMAGE=ghcr.io/silvesterlubwama/connect-frontend:v0.1.0
APP_VERSION=appliance-bootstrap
EOF
    chmod 600 .env
else
    log ".env already exists — leaving it alone."
fi

# ── 4. Pull + start ──────────────────────────────────────────────
log "Pulling latest images…"
docker compose pull

log "Starting stack (this may take a minute on first run)…"
docker compose up -d

# ── 5. Wait for /healthz ─────────────────────────────────────────
log "Waiting for /healthz…"
for i in $(seq 1 60); do
    if curl -fsS http://127.0.0.1/healthz >/dev/null 2>&1; then
        break
    fi
    sleep 2
    [ "$i" = 60 ] && warn "/healthz didn't respond within 2 minutes — check 'docker compose logs'"
done

# ── 6. Show URLs ─────────────────────────────────────────────────
LAN_IP="$(hostname -I | awk '{print $1}')"
cat <<EOM

────────────────────────────────────────────────────────────────────
  58:12 Connect appliance is up.

  LAN access:
    http://${LAN_IP}
    http://$(hostname -s).local        (mDNS, where supported)

  Useful commands:
    sudo docker compose -f $APPLIANCE/docker-compose.yml ps
    sudo docker compose -f $APPLIANCE/docker-compose.yml logs -f
    sudo docker compose -f $APPLIANCE/docker-compose.yml restart
    sudo docker compose -f $APPLIANCE/docker-compose.yml down

  Edit $APPLIANCE/.env to enable:
    - Public TLS hostname (SITE_DOMAIN)
    - Cloudflare Tunnel for remote access (CLOUDFLARED_TOKEN)
    - Email / OCR / Sentry integrations

  Default admin login:
    Email:    admin@5812uganda.org
    Password: Admin@5812
  >>> Rotate this password under Settings → Security before going live. <<<
────────────────────────────────────────────────────────────────────
EOM
